
project:
  type: website
  output-dir: docs

website:
  title: "IMAG — Investment Management & Asset Game"
  navbar:
    left:
      - text: "Project"
        href: project.qmd
      - text: "Team"
        href: team.qmd
      - text: "Outcomes"
        href: outcomes.qmd
      - text: "Events"
        href: events.qmd
      - text: "Apps"
        href: apps.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: cosmo
    css: assets/css/unpie-like.css
    toc: false
