project:
  type: website
  output-dir: ../docs/slides

website:
  title: "IMAG Slides"
  navbar: false

format:
  revealjs:
    slide-number: true
    toc: false
    include-in-header: ../includes/head.html
    include-before-body: ../includes/header.html
    include-after-body: ../includes/footer.html
    transition: fade
    theme: default
    width: 1280
    height: 720
    css: custom.css
    footer: "<div class='slide-footer-logos'><img src='../assets/logos/uli.jpg' alt='uni.li'><img src='../assets/logos/unibz.jpg' alt='unibz'><img src='../assets/logos/cesim.png' alt='Cesim'><img src='../assets/logos/erasmus.jpg' alt='Erasmus+'></div>"
