<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10&nbsp; Security Analysis – IMAG Teaching Materials</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./11_Portfolio_Implementation.html" rel="next">
<link href="./09_Tactical_Asset_Allocation.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-30dd83e0b6319156608325edb9fc2c35.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="custom.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <a class="flex-grow-1 no-decor" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
          <h1 class="quarto-secondary-nav-title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Security Analysis</span></h1>
        </a>     
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">IMAG Teaching Materials</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">IMAG Teaching Materials</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_Introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_Asset_Classes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Asset Classes, Currencies and Instruments</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_Sustainable_Investing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Sustainable Investing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_Client_Analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Client Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_Investment_Policy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Investment Policy</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_Strategic_Fiancial_Analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Strategic Financial Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_Strategic_Asset_Allocation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Strategic Asset Allocation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_Tactical_Financial_Analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Tactical Financial Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_Tactical_Asset_Allocation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Tactical Asset Allocation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_Security_Analysis.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Security Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_Portfolio_Implementation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Portfolio Implementation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12_Portfolio_Analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Performance Analysis</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">10.1</span> Introduction</a></li>
  <li><a href="#fundamental-equity-analysis-the-bottom-up-approach" id="toc-fundamental-equity-analysis-the-bottom-up-approach" class="nav-link" data-scroll-target="#fundamental-equity-analysis-the-bottom-up-approach"><span class="header-section-number">10.2</span> Fundamental Equity Analysis: The Bottom-Up Approach</a>
  <ul class="collapse">
  <li><a href="#reading-the-ratios-a-worked-example" id="toc-reading-the-ratios-a-worked-example" class="nav-link" data-scroll-target="#reading-the-ratios-a-worked-example"><span class="header-section-number">10.2.1</span> Reading the Ratios: A Worked Example</a></li>
  <li><a href="#valuation" id="toc-valuation" class="nav-link" data-scroll-target="#valuation"><span class="header-section-number">10.2.2</span> Valuation</a></li>
  <li><a href="#qualitative-factors" id="toc-qualitative-factors" class="nav-link" data-scroll-target="#qualitative-factors"><span class="header-section-number">10.2.3</span> Qualitative Factors</a></li>
  <li><a href="#esg-as-a-quality-overlay" id="toc-esg-as-a-quality-overlay" class="nav-link" data-scroll-target="#esg-as-a-quality-overlay"><span class="header-section-number">10.2.4</span> ESG as a Quality Overlay</a></li>
  </ul></li>
  <li><a href="#quantitative-equity-analysis-multi-factor-models" id="toc-quantitative-equity-analysis-multi-factor-models" class="nav-link" data-scroll-target="#quantitative-equity-analysis-multi-factor-models"><span class="header-section-number">10.3</span> Quantitative Equity Analysis: Multi-Factor Models</a></li>
  <li><a href="#fixed-income-analysis-government-and-corporate-bonds" id="toc-fixed-income-analysis-government-and-corporate-bonds" class="nav-link" data-scroll-target="#fixed-income-analysis-government-and-corporate-bonds"><span class="header-section-number">10.4</span> Fixed Income Analysis: Government and Corporate Bonds</a></li>
  <li><a href="#analyzing-alternative-assets-commodities-and-cryptocurrencies" id="toc-analyzing-alternative-assets-commodities-and-cryptocurrencies" class="nav-link" data-scroll-target="#analyzing-alternative-assets-commodities-and-cryptocurrencies"><span class="header-section-number">10.5</span> Analyzing Alternative Assets: Commodities and Cryptocurrencies</a></li>
  <li><a href="#security-selection-in-a-portfolio-context" id="toc-security-selection-in-a-portfolio-context" class="nav-link" data-scroll-target="#security-selection-in-a-portfolio-context"><span class="header-section-number">10.6</span> Security Selection in a Portfolio Context</a></li>
  <li><a href="#case-study-selecting-the-schmidt-miller-securities" id="toc-case-study-selecting-the-schmidt-miller-securities" class="nav-link" data-scroll-target="#case-study-selecting-the-schmidt-miller-securities"><span class="header-section-number">10.7</span> Case Study: Selecting the Schmidt-Miller Securities</a></li>
  <li><a href="#security-analysis-in-imag" id="toc-security-analysis-in-imag" class="nav-link" data-scroll-target="#security-analysis-in-imag"><span class="header-section-number">10.8</span> Security Analysis in IMAG</a>
  <ul class="collapse">
  <li><a href="#from-tactical-weights-to-asset-level-positions" id="toc-from-tactical-weights-to-asset-level-positions" class="nav-link" data-scroll-target="#from-tactical-weights-to-asset-level-positions"><span class="header-section-number">10.8.1</span> From Tactical Weights to Asset-Level Positions</a></li>
  <li><a href="#evaluating-security-selection" id="toc-evaluating-security-selection" class="nav-link" data-scroll-target="#evaluating-security-selection"><span class="header-section-number">10.8.2</span> Evaluating Security Selection</a></li>
  <li><a href="#applying-the-chapter-framework" id="toc-applying-the-chapter-framework" class="nav-link" data-scroll-target="#applying-the-chapter-framework"><span class="header-section-number">10.8.3</span> Applying the Chapter Framework</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Security Analysis</span></h1>
</div>



<div class="quarto-title-meta column-body">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-tip callout-titled" title="Lecture Slides">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Lecture Slides
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Associated slides:</strong> <a href="../slides/lesson-05-taa-security.html">Lesson 5 — Tactical Allocation &amp; Security Selection</a></p>
</div>
</div>
<section id="introduction" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">10.1</span> Introduction</h2>
<p>The preceding chapters moved from the client’s circumstances to the strategic asset allocation. We established the policy mix. We examined tactical tilts. We addressed the constraints of implementation. What remains is the final step: selecting the specific securities that will populate each asset class allocation.</p>
<p>Security analysis is the process of evaluating individual investments for their suitability. It asks not whether equities as a class are attractive, but whether a particular stock, bond, or fund merits the capital it would receive. The strategic allocation provides the architecture. Security analysis provides the materials. A sound allocation can be undermined by poor security selection, just as a well-designed building can be compromised by faulty materials.</p>
<p>This distinction connects directly to the Brinson-Fachler attribution framework from Chapter 9. Recall that the model decomposes active return into allocation effects and selection effects. The allocation effect captures whether overweighting or underweighting an asset class added value. The selection effect captures whether the specific securities chosen within that asset class beat its benchmark. Security analysis feeds the selection effect. It is the engine that drives the <span class="math inline">\(R_{p,i} - R_{b,i}\)</span> term in the Brinson-Fachler formula. A positive selection effect means the securities chosen outperformed the asset class benchmark. Security analysis is the discipline that seeks to make that happen.</p>
<p>At its core, security analysis rests on a simple distinction: intrinsic value versus market price. Intrinsic value is what an asset is worth, based on its expected future cash flows, its risk, and its growth prospects. Market price is what the market is willing to pay for it today. The two are not always equal. Markets are mostly efficient, as Chapter 8 discussed, but they are not perfectly efficient. Sentiment, liquidity, and institutional constraints can push prices away from intrinsic value. Security analysis seeks to identify those gaps, to buy assets trading below their intrinsic value and to avoid or sell those trading above it.</p>
<p>The approach taken depends on the asset class. For equities, fundamental analysis examines financial statements, competitive position, and management quality. For bonds, credit analysis assesses the issuer’s ability to meet its obligations. For funds and ETFs, the analysis shifts to the manager’s process, the fee structure, and the tracking error relative to the benchmark. Each asset class requires its own analytical framework, but the underlying question is the same: is this security priced in a way that compensates us adequately for the risks we are taking?</p>
<p>This chapter surveys the methods of security analysis. We begin with the macroeconomic context, then examine fundamental equity analysis, fixed income analysis, and quantitative screening approaches. The treatment is not exhaustive—entire textbooks are devoted to each method—but it provides the framework within which security selection decisions are made. The chapter concludes by populating the Schmidt-Miller portfolio with specific securities, translating the strategic weights from Chapter 7 into a concrete set of holdings.</p>
</section>
<section id="fundamental-equity-analysis-the-bottom-up-approach" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="fundamental-equity-analysis-the-bottom-up-approach"><span class="header-section-number">10.2</span> Fundamental Equity Analysis: The Bottom-Up Approach</h2>
<p>Fundamental equity analysis seeks to determine the intrinsic value of a company by examining its financial statements, its competitive position, and its prospects for future growth. It is a bottom-up approach. It begins with the company itself, not with the economy or the sector, though both provide context for the assessment.</p>
<p>Financial statement analysis forms the foundation. The three primary statements—the income statement, the balance sheet, and the cash flow statement—tell the story of a business in numbers. Revenue growth reveals whether the company is expanding or stagnating. Profit margins reveal its pricing power and cost discipline. Return on equity reveals how efficiently it deploys shareholder capital. But the raw numbers are only a starting point. The analyst must assess their quality.</p>
<p>Quality of earnings refers to the sustainability and reliability of reported profits. A company that consistently meets or beats earnings estimates may be managing earnings through aggressive revenue recognition, changes in inventory accounting, or the timing of expenses. Cash flow conversion provides a check. If reported earnings are strong but operating cash flow is weak, the earnings may be of low quality. The cash flow statement strips away non-cash items and reveals how much actual cash the business generates. A high ratio of operating cash flow to net income suggests that earnings are backed by real cash. A low ratio suggests the opposite.</p>
<p>Capital structure analysis examines how the company finances its operations. The mix of debt and equity affects both risk and return. High leverage amplifies returns when business conditions are favorable but increases the risk of financial distress when they deteriorate. The analyst assesses whether the company’s debt load is sustainable given its cash flow, the maturity profile of its obligations, and the covenants that govern its borrowing.</p>
<section id="reading-the-ratios-a-worked-example" class="level3" data-number="10.2.1">
<h3 data-number="10.2.1" class="anchored" data-anchor-id="reading-the-ratios-a-worked-example"><span class="header-section-number">10.2.1</span> Reading the Ratios: A Worked Example</h3>
<p>The ratios that drive this analysis are most useful when read as a set. Consider a European financials company. The table below presents five years of selected fundamentals.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 20%">
<col style="width: 19%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Last year</th>
<th>Two years ago</th>
<th>Three years ago</th>
<th>Four years ago</th>
<th>Five years ago</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Earnings per share, EUR</td>
<td>11.24</td>
<td>6.01</td>
<td>4.78</td>
<td>−4.35</td>
<td>6.03</td>
</tr>
<tr class="even">
<td>Price-to-earnings</td>
<td>11.38</td>
<td>16.16</td>
<td>20.94</td>
<td>−18.73</td>
<td>39.86</td>
</tr>
<tr class="odd">
<td>Return on equity, %</td>
<td>16.89</td>
<td>8.87</td>
<td>7.17</td>
<td>−5.29</td>
<td>7.13</td>
</tr>
<tr class="even">
<td>Debt-to-equity</td>
<td>774.42</td>
<td>1039.81</td>
<td>1043.16</td>
<td>1111.11</td>
<td>1206.94</td>
</tr>
<tr class="odd">
<td>Dividend yield, %</td>
<td>1.56</td>
<td>1.80</td>
<td>1.50</td>
<td>1.84</td>
<td>0.56</td>
</tr>
<tr class="even">
<td>Free cash flow per share, EUR</td>
<td>78.94</td>
<td>24.30</td>
<td>13.25</td>
<td>−5.04</td>
<td>−5.38</td>
</tr>
<tr class="odd">
<td>Revenue, m EUR</td>
<td>93,194</td>
<td>91,688</td>
<td>89,315</td>
<td>92,232</td>
<td>85,397</td>
</tr>
<tr class="even">
<td>Operating margin, %</td>
<td>14.21</td>
<td>10.90</td>
<td>7.51</td>
<td>5.62</td>
<td>10.17</td>
</tr>
</tbody>
</table>
<p>The individual numbers tell different stories depending on which year you look at. Read as a trend, they tell one story: a business that deteriorated sharply four years ago, then recovered, and is now operating at levels well above where it stood before the downturn.</p>
<p>Start with earnings. Five years ago, the company earned €6.03 per share. Four years ago, it lost €4.35 per share. That swing, from positive to negative earnings, is the most important fact in the table. It is what the rest of the ratios are responding to. The loss depressed return on equity to −5.29 percent and produced a negative price-to-earnings ratio, which occurs whenever earnings are negative and the ratio becomes mathematically meaningless. The recovery that followed—€4.78, then €6.01, then €11.24—restored profitability and brought the P/E back into a normal range.</p>
<p>The trajectory of free cash flow per share is more striking still. It went from −€5.38 five years ago to €78.94 last year. That is not a typo. A financials company can generate large swings in cash flow as balance sheet positions turn over, and the recovery from a loss year can produce cash flow that far exceeds reported earnings. The analyst’s task is to determine how much of that €78.94 represents sustainable cash generation and how much reflects one-time reversals or balance sheet effects. If the cash flow is durable, the quality of earnings is high and the recovery is real. If it is not, the earnings may be paper gains.</p>
<p>Debt-to-equity tells the deleveraging story. Five years ago the ratio stood at 1,206.94. It has fallen to 774.42. For a financials company, a debt-to-equity ratio in the high hundreds is not unusual—banks and insurers operate with leverage that would be alarming in an industrial. The relevant question is not whether the absolute level is high but whether it is falling and whether the trend is sustainable. It is falling, and steadily. The analyst notes the direction and asks what is driving it: retained earnings, asset sales, or a deliberate reduction in risk-weighted assets.</p>
<p>Operating margin shows the recovery in profitability at the operating level. It bottomed at 5.62 percent four years ago and has climbed to 14.21 percent. Revenue, by contrast, has barely moved. The company is not growing its top line. It is improving its margins. The analyst must judge whether margin expansion can continue or whether it has run its course. If the improvement came from cost cuts, there is a limit to how much more can be extracted. If it came from a shift in business mix toward higher-margin activities, the improvement may be more durable.</p>
<p>The dividend yield is modest, 1.56 percent, and has been stable across the period. The company maintained its dividend even during the loss year, which tells the analyst something about management’s commitment to shareholder returns—and about the strength of its capital position. A company that can sustain a dividend through a loss year is not in distress.</p>
<p>The P/E ratio of 11.38 requires interpretation. Is the company cheap? Relative to the broader European financials sector, a P/E in the low teens may be normal. Relative to its own history, the current multiple is well below the 39.86 of five years ago and the 20.94 of three years ago. But those prior multiples were calculated on much lower earnings, and the ratio is mechanically distorted by the loss year. The relevant comparison is the current P/E against the sector and against the company’s own sustainable earnings power, not against ratios computed during a period of depressed or negative earnings.</p>
<p>The final layer of analysis is the four-factor model. The table reports the company’s factor betas as of the last round.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Factor</th>
<th>Beta</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Alpha, %</td>
<td>0.18</td>
</tr>
<tr class="even">
<td>Market beta</td>
<td>0.93</td>
</tr>
<tr class="odd">
<td>HML beta</td>
<td>−0.01</td>
</tr>
<tr class="even">
<td>MOM beta</td>
<td>−0.27</td>
</tr>
<tr class="odd">
<td>RMW beta</td>
<td>−0.31</td>
</tr>
</tbody>
</table>
<p>The market beta of 0.93 is close to one, meaning the stock moves roughly in line with the market. The HML beta of −0.01 is neutral on value versus growth—the stock is neither strongly value-tilted nor strongly growth-tilted, despite the low P/E. The negative MOM beta of −0.27 indicates that the stock has not participated in recent momentum, which is consistent with a recovery story that has not yet been fully recognized by the market. The negative RMW beta of −0.31 is the most interesting. RMW stands for Robust Minus Weak, the profitability factor. A negative loading means the stock is tilted toward less profitable companies. Yet the ROE of 16.89 percent is strong by any standard. The discrepancy suggests that the profitability factor is capturing something the trailing ROE does not—perhaps the volatility of earnings across the cycle, or the capital intensity of the business, or the market’s judgment that current profitability is not sustainable.</p>
<p>This is the kind of tension that separates mechanical factor screening from genuine analysis. A purely quantitative screen would flag the negative RMW loading as a negative signal and reduce the position. A fundamental analyst would look at the ROE and the FCF trajectory and conclude the opposite. The resolution comes from understanding what the factor is measuring and whether that measurement is informative in this particular case. Factor models are tools. They do not replace judgment.</p>
<p>The worked example illustrates the discipline that financial statement analysis requires. Each ratio is meaningless in isolation. The P/E of 11.38 looks cheap, but not if earnings are about to decline. The ROE of 16.89 looks strong, but not if it is the peak of a cyclical recovery. The FCF of €78.94 per share looks impressive, but not if it cannot be repeated. The analyst’s job is to construct a coherent narrative that explains the ratios and to test that narrative against the qualitative factors that numbers cannot capture.</p>
</section>
<section id="valuation" class="level3" data-number="10.2.2">
<h3 data-number="10.2.2" class="anchored" data-anchor-id="valuation"><span class="header-section-number">10.2.2</span> Valuation</h3>
<p>Valuation translates the analysis of the business into an estimate of what its shares are worth. Two broad approaches exist. Absolute valuation models estimate intrinsic value directly, based on the present value of expected future cash flows. Relative valuation models compare the company’s pricing multiples to those of similar firms. Both approaches require a discount rate, and the choice of discount rate depends on which cash flows are being discounted.</p>
<p>The distinction between the cost of equity and the weighted average cost of capital is essential. When valuing equity directly, by discounting free cash flow to equity, the appropriate discount rate is the cost of equity, derived from the CAPM or a multi-factor model. When valuing the entire enterprise, by discounting free cash flow to the firm, the appropriate discount rate is the weighted average cost of capital, or WACC. The WACC blends the cost of equity and the after-tax cost of debt, weighted by their proportions in the company’s capital structure:</p>
<p><span class="math display">\[
\text{WACC} = \frac{E}{E + D} \cdot r_e + \frac{D}{E + D} \cdot r_d \cdot (1 - t)
\]</span></p>
<p>Where <span class="math inline">\(E\)</span> is the market value of equity, <span class="math inline">\(D\)</span> is the market value of debt, <span class="math inline">\(r_e\)</span> is the cost of equity, <span class="math inline">\(r_d\)</span> is the cost of debt, and <span class="math inline">\(t\)</span> is the corporate tax rate. The tax shield on debt reduces the effective cost of borrowing, reflecting the deductibility of interest payments in most jurisdictions. A company with significant debt financing will have a WACC below its cost of equity, all else equal.</p>
<section id="the-discounted-cash-flow-model" class="level4">
<h4 class="anchored" data-anchor-id="the-discounted-cash-flow-model">The Discounted Cash Flow Model</h4>
<p>The discounted cash flow framework is the foundation of all valuation. It expresses the value of any asset as the present value of its expected future cash flows. For equities, those cash flows are dividends or free cash flow to equity. The analyst projects them over an explicit forecast period, typically five to ten years, and then estimates a terminal value to capture everything beyond the forecast horizon.</p>
<p>The model in its equity form is written as:</p>
<p><span class="math display">\[
V_0 = \sum_{t=1}^{n} \frac{FCFE_t}{(1 + r_e)^t} + \frac{TV}{(1 + r_e)^n}
\]</span></p>
<p>Where <span class="math inline">\(FCFE_t\)</span> is the free cash flow to equity in year <span class="math inline">\(t\)</span>, <span class="math inline">\(r_e\)</span> is the cost of equity, and <span class="math inline">\(TV\)</span> is the terminal value. The cost of equity comes from the CAPM or a multifactor model, as discussed in Chapter 6. The forecast period is long enough to reach a steady state, where growth, margins, and reinvestment have normalized. Everything before that point is projected year by year, with separate assumptions for revenue growth, operating margin, capital expenditure, working capital changes, and net borrowing.</p>
<p>The model can also be applied to the enterprise rather than to equity directly. In that form, the analyst projects free cash flow to the firm—the cash available to all capital providers, both equity and debt holders—and discounts at the WACC. The resulting enterprise value is then reduced by net debt to arrive at equity value. The two approaches should produce the same answer if the assumptions are consistent. In practice, the enterprise approach is more common for companies with significant debt or changing capital structure, because it avoids the need to forecast financing flows separately.</p>
<p>The terminal value typically accounts for more than half of the total valuation. This is not a flaw in the model. It reflects the reality that most of a company’s value comes from cash flows beyond the explicit forecast horizon. But it means that small changes in the terminal assumptions produce large changes in the estimated value. The terminal value is usually calculated using the Gordon Growth Model:</p>
<p><span class="math display">\[
TV = \frac{FCFE_{n+1}}{r_e - g}
\]</span></p>
<p>Where <span class="math inline">\(g\)</span> is the perpetual growth rate. The Gordon Growth Model (Gordon, 1959) provides the mathematical link between a company’s required return, its cash flow, and its long-term growth rate. The constraint is that <span class="math inline">\(g\)</span> must be less than <span class="math inline">\(r_e\)</span>, or the formula produces a negative or infinite value. In practice, <span class="math inline">\(g\)</span> is set close to the long-run growth rate of the economy—typically 2 to 3 percent for a developed market—because no company can grow faster than the economy forever. An analyst who assumes a perpetual growth rate above the long-run rate is implicitly assuming that the company eventually becomes larger than the economy.</p>
<p>An alternative to the Gordon Growth Model is the exit multiple approach. Instead of assuming a perpetual growth rate, the analyst assumes that the company will be sold at the end of the forecast period for a multiple of some financial metric—EBITDA, earnings, or book value—based on the multiples at which comparable companies currently trade. This approach anchors the terminal value in observable market pricing rather than in a growth assumption. Its weakness is that it assumes the exit multiple will be whatever the analyst chooses, and a terminal value based on a rich exit multiple can hide an otherwise undemanding valuation.</p>
<p>The DCF process is intensive. It requires detailed projections of revenue, margins, capital expenditures, and working capital. It requires assumptions about the long-term growth rate, the appropriate discount rate, and the terminal multiple or growth rate. Small changes in any of these can produce large changes in the estimated value. The analyst who builds a DCF is not producing a precise number. The analyst is producing a framework within which the key drivers of value can be identified and tested.</p>
<p>Sensitivity analysis makes this explicit. Rather than presenting a single intrinsic value estimate, the analyst varies the key assumptions across a plausible range and observes how the estimated value responds. A typical sensitivity table shows intrinsic value as a function of the discount rate and the terminal growth rate, each varied across a grid. The pattern of results is often more informative than any single cell. If the intrinsic value remains comfortably above the market price across the full range of reasonable assumptions, the margin of safety is robust. If the intrinsic value crosses the market price within that range, the valuation is fragile and the investment case depends on assumptions that may not hold.</p>
<p>For the European financials company in the worked example, a standard DCF is difficult to apply. The free cash flow per share has swung from −€5.38 to €78.94 over five years, and a financials company’s cash flows are driven by balance sheet turnover in ways that a standard FCFE forecast does not capture well. The residual income model, discussed below, is usually a better fit for banks and insurers. The DCF framework still applies in principle—the value of the equity is still the present value of the cash flows accruing to shareholders—but the practical implementation requires a different projection structure than the one used for an industrial company.</p>
</section>
<section id="the-residual-income-model" class="level4">
<h4 class="anchored" data-anchor-id="the-residual-income-model">The Residual Income Model</h4>
<p>The residual income model offers an alternative to the DCF. It values equity directly as the sum of current book value and the present value of future residual income—the earnings that exceed the required return on equity:</p>
<p><span class="math display">\[
V_0 = B_0 + \sum_{t=1}^{n} \frac{RI_t}{(1 + r_e)^t} + \frac{TV}{(1 + r_e)^n}
\]</span></p>
<p>Where <span class="math inline">\(B_0\)</span> is the current book value of equity, <span class="math inline">\(RI_t\)</span> is residual income in year <span class="math inline">\(t\)</span>, and <span class="math inline">\(r_e\)</span> is the cost of equity. Residual income is defined as net income less the equity charge, which is the cost of equity multiplied by the beginning book value. In other words, a company creates value only to the extent that it earns more than its shareholders could earn elsewhere at equivalent risk.</p>
<p>The residual income model is particularly useful for financial companies, where book value is a meaningful metric, and for companies that do not generate positive free cash flow. For the European financials company in the worked example, the residual income model may be more appropriate than a standard DCF. The large swings in free cash flow per share make it difficult to project a stable FCFE stream, but book value is well defined for a bank or insurer, and return on equity—the key driver of residual income—is directly observable and has been recovering steadily. The current ROE of 16.89 percent, against an assumed cost of equity in the range of 8 to 10 percent, implies that the company is generating positive residual income. Whether that will continue depends on the sustainability of the recovery and the discipline of management’s capital allocation, which the qualitative analysis is designed to assess.</p>
</section>
<section id="relative-valuation" class="level4">
<h4 class="anchored" data-anchor-id="relative-valuation">Relative Valuation</h4>
<p>Relative valuation sidesteps the complexity of forecasting cash flows. It values a company by comparing its pricing multiples to those of comparable firms. The price-to-earnings ratio, or P/E, is the most common. A company trading at a lower P/E than its peers may be undervalued, or it may deserve a lower multiple because of slower growth, higher risk, or poorer management. Enterprise value to EBITDA, or EV/EBITDA, is popular precisely because it uses the enterprise value, reflecting the claims of both equity and debt holders, and a measure of operating profit before depreciation and amortization. This neutrality toward capital structure makes it easier to compare companies with different levels of debt. Price-to-book, or P/B, is used for asset-heavy industries like banking and insurance. Each multiple has strengths and weaknesses. The skilled analyst uses several in combination, looking for consistency across metrics rather than relying on any single one.</p>
<p>For the financials company in the worked example, the relevant peer group would be European banks and insurers with similar business mixes. The P/E of 11.38 would be compared to the sector median. The debt-to-equity of 774.42 would be assessed against the leverage norms of the peer group. The ROE of 16.89 percent would be compared to the sector’s average return on equity. If the company trades at a discount to peers on P/E while delivering a higher ROE, it may be undervalued. If the discount reflects a lower-quality earnings stream, higher risk, or weaker growth prospects, the discount may be justified.</p>
</section>
</section>
<section id="qualitative-factors" class="level3" data-number="10.2.3">
<h3 data-number="10.2.3" class="anchored" data-anchor-id="qualitative-factors"><span class="header-section-number">10.2.3</span> Qualitative Factors</h3>
<p>Qualitative factors are harder to measure but no less important. A company’s competitive position—its moat—determines whether it can sustain its profits against rivals. Porter’s Five Forces framework assesses the threat of new entrants, the bargaining power of suppliers and customers, the threat of substitute products, and the intensity of rivalry within the industry. A wide moat, built on brand strength, switching costs, network effects, or cost advantages, protects profitability and justifies a higher valuation.</p>
<p>Management quality matters. A skilled management team allocates capital wisely, invests in projects that earn returns above the cost of capital, and communicates honestly with shareholders. A poor management team destroys value through ill-considered acquisitions, excessive compensation, or strategic missteps. Assessing management requires reading earnings call transcripts, shareholder letters, and the track record of capital allocation decisions over time. The cost of capital is not merely a mechanical input to a DCF model. It is the hurdle rate against which management’s investment decisions should be judged. A management team that consistently earns returns above the WACC creates value. One that earns returns below it destroys value, regardless of how rapidly earnings are growing.</p>
<p>The financials company in the worked example offers a case in point. The debt-to-equity ratio has fallen from 1,206.94 to 774.42 over five years. That deleveraging did not happen by accident. It reflects a series of decisions about which businesses to grow, which to shrink, and how to allocate capital across the balance sheet. The analyst who wants to understand whether the improvement is sustainable must understand those decisions. Was the reduction in leverage achieved by selling assets, by retaining earnings, or by reducing the risk profile of the loan book? Each path implies a different forward trajectory. The numbers show what happened. The narrative explains why, and whether it will continue.</p>
<p>Scalability of the business model determines the pace at which growth can be achieved. A software company with a product that can be distributed globally at near-zero marginal cost can grow far faster than a manufacturing company that must build new factories to increase output. The market size, the competitive landscape, and the company’s ability to execute all factor into the growth assumptions that drive the valuation.</p>
</section>
<section id="esg-as-a-quality-overlay" class="level3" data-number="10.2.4">
<h3 data-number="10.2.4" class="anchored" data-anchor-id="esg-as-a-quality-overlay"><span class="header-section-number">10.2.4</span> ESG as a Quality Overlay</h3>
<p>ESG analysis enters the fundamental framework as an overlay on the qualitative assessment. The financials company in the worked example reports ESG scores that have improved materially over four years.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 23%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th>Score type</th>
<th>Last year</th>
<th>Two years ago</th>
<th>Three years ago</th>
<th>Four years ago</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Environmental</td>
<td>90.76</td>
<td>59.44</td>
<td>61.25</td>
<td>28.38</td>
</tr>
<tr class="even">
<td>Social</td>
<td>69.15</td>
<td>53.48</td>
<td>5.90</td>
<td>14.71</td>
</tr>
<tr class="odd">
<td>Governance</td>
<td>84.23</td>
<td>86.20</td>
<td>48.98</td>
<td>76.91</td>
</tr>
<tr class="even">
<td>Overall</td>
<td>73.53</td>
<td>63.59</td>
<td>26.73</td>
<td>37.63</td>
</tr>
</tbody>
</table>
<p>The overall score has risen from 26.73 to 73.53. The environmental score has more than tripled. The governance score, already reasonably strong four years ago, has been maintained. The social score shows the most dramatic improvement, from 5.90 three years ago to 69.15 last year—a swing large enough to warrant scrutiny. Scores that improve this quickly can reflect genuine operational change, or they can reflect changes in disclosure and reporting. The analyst’s task is to distinguish the two. If the improvement came from new policies, new leadership, or new business practices, it may signal a durable reduction in risk. If it came primarily from expanded reporting, the underlying risk may be unchanged.</p>
<p>For a financials company, governance is the most material of the three dimensions. Board independence, risk management practices, and executive compensation structures determine whether the institution can weather periods of stress without requiring external support. The governance score of 84.23 is strong. Combined with the falling leverage and improving profitability, it suggests an institution that has strengthened its foundations since the loss year. This is the kind of qualitative signal that supports a positive view of the security, not because ESG is a separate criterion but because it is informative about the risks that the financial statements may not yet fully reflect.</p>
<p>Fundamental equity analysis ends with a decision. If the estimated intrinsic value exceeds the market price by a sufficient margin of safety, the stock is a candidate for purchase. If the market price exceeds intrinsic value, it is a candidate for sale or avoidance. The margin of safety protects against errors in the analysis. No valuation is precise. The analyst who demands a discount to intrinsic value before buying builds a cushion against the unknown. That discipline is at the heart of fundamental investing.</p>
</section>
</section>
<section id="quantitative-equity-analysis-multi-factor-models" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="quantitative-equity-analysis-multi-factor-models"><span class="header-section-number">10.3</span> Quantitative Equity Analysis: Multi-Factor Models</h2>
<p>Fundamental analysis examines one company at a time. Quantitative analysis examines thousands. It uses statistical models to identify characteristics that explain differences in returns across securities. Where the fundamental analyst reads annual reports, the quantitative analyst runs regressions.</p>
<p>The shift began with the recognition that the Capital Asset Pricing Model, introduced in Chapter 6, provides an incomplete description of equity returns. Beta captures sensitivity to the market portfolio, but it does not capture everything. Stocks with similar betas can have very different returns if they differ on other dimensions. This observation gave rise to Arbitrage Pricing Theory and, from there, to the multi-factor models that now dominate quantitative equity analysis.</p>
<p>The Fama-French framework is the cornerstone. It begins with the market factor from the CAPM and adds two additional factors: size and value. The size factor, called SMB for Small Minus Big, captures the historical tendency of smaller companies to outperform larger ones. The value factor, called HML for High Minus Low, captures the tendency of companies with high book-to-market ratios—value stocks—to outperform those with low ratios—growth stocks.</p>
<p>The three-factor model expresses expected return as:</p>
<p><span class="math display">\[
E(R_i) = R_f + \beta_i [E(R_m) - R_f] + s_i \cdot \text{SMB} + h_i \cdot \text{HML}
\]</span></p>
<p>Where <span class="math inline">\(s_i\)</span> is the stock’s sensitivity to the size factor and <span class="math inline">\(h_i\)</span> is its sensitivity to the value factor. A small-cap value stock would have positive loadings on both SMB and HML. A large-cap growth stock would have negative loadings on both.</p>
<p>The three-factor model was a significant improvement over the CAPM. It explained a larger portion of the cross-sectional variation in equity returns. But it was not complete. Subsequent research identified additional factors. The momentum factor, WML for Winners Minus Losers, captures the tendency of stocks that have performed well in the recent past to continue performing well in the near term. The quality factor, often measured as RMW for Robust Minus Weak, captures the tendency of companies with strong profitability, low leverage, and stable earnings to deliver higher risk-adjusted returns.</p>
<p>A five-factor model incorporating market, size, value, profitability, and investment has become the standard in academic research. In practice, different managers emphasize different factors based on their investment philosophy and the evidence they find most compelling.</p>
<p>The worked example from the previous section shows how the factor betas are reported for a single security. The HML beta of −0.01, the MOM beta of −0.27, and the RMW beta of −0.31 together place the stock in a specific region of factor space: neutral on value, negative on momentum, negative on profitability. That profile is unusual for a company with a low P/E and a high ROE. It suggests that the market is pricing in something that the trailing financials do not capture—perhaps uncertainty about the sustainability of the recovery, or a view that the profitability is cyclical rather than structural. Whether the factor profile is a signal to avoid the stock or an opportunity to buy a misunderstood business depends on the analyst’s view of the underlying fundamentals. The factors describe. They do not prescribe.</p>
<p>Factor tilting translates this framework into portfolio construction. Each stock in the universe is assigned a score on each factor. The scores are typically expressed as Z-scores, measuring how many standard deviations the stock’s characteristic lies from the cross-sectional mean. A stock with a high book-to-market ratio, a low market capitalization, and strong recent momentum would score positively on value, size, and momentum. A stock with the opposite characteristics would score negatively.</p>
<p>The quantitative analyst combines these scores into a composite signal. The weights assigned to each factor reflect the analyst’s conviction and the empirical evidence on factor efficacy. The composite signal ranks stocks from most attractive to least attractive. The portfolio overweights the former and underweights or excludes the latter.</p>
<p>Factor tilting is not without challenges. Factor premiums vary over time. A value tilt that underperforms for years tests the conviction of the manager and the patience of the client. Momentum can reverse violently when market conditions change. The factors themselves can become crowded, as the growing popularity of factor-based strategies compresses the premiums they seek to capture.</p>
<p>These challenges do not invalidate the approach. They counsel humility in its application. Factor tilts should be modest, diversified across multiple factors, and evaluated over full market cycles. The quantitative analyst who expects every factor to work every year will be disappointed. The analyst who understands that factor premiums are compensation for bearing systematic risk—and that risk sometimes shows up—will be better prepared for the inevitable periods of underperformance.</p>
<p>The rise of multi-factor investing has blurred the line between active and passive management. A portfolio that tilts systematically toward value, size, and quality is not actively managed in the traditional sense. It does not rely on stock-specific research or market timing. But neither is it passive, in the sense of simply tracking a market-cap-weighted index. It occupies a middle ground, sometimes called smart beta or factor investing. For the Schmidt-Miller portfolio, this approach offers a way to pursue incremental returns within the equity allocation without the higher costs and concentration risk of traditional active management.</p>
</section>
<section id="fixed-income-analysis-government-and-corporate-bonds" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="fixed-income-analysis-government-and-corporate-bonds"><span class="header-section-number">10.4</span> Fixed Income Analysis: Government and Corporate Bonds</h2>
<p>Equity analysis seeks to estimate future cash flows and the discount rate at which they should be valued. Fixed income analysis, by contrast, deals largely in contractual cash flows. The coupon payments and principal repayment are specified in advance, at least for bonds free of default risk. This certainty shifts the analytical focus from forecasting growth to measuring risk. Interest rate risk and credit risk dominate the fixed income landscape.</p>
<p>The return on a bond comes from three sources. The first is the yield, the coupon income earned on the bond’s face value. For a government bond held to maturity with no default, the yield to maturity at the time of purchase is the primary driver of return. The second source is rolldown. As a bond ages and its maturity shortens, its yield typically declines along the yield curve. The bond’s price rises as it rolls down the curve, adding to total return even if the level of interest rates remains unchanged. The third source is the change in spreads, relevant for bonds that carry credit risk. When a bond’s credit spread narrows, its price rises relative to otherwise similar government bonds. When spreads widen, the price falls.</p>
<p>These components decompose the return into what is earned passively, through the passage of time and the receipt of coupons, and what is earned actively, through changes in the interest rate and credit environment.</p>
<p>Interest rate risk is measured by duration and convexity. Duration captures the sensitivity of a bond’s price to a small change in its yield. Modified duration provides an approximation of the percentage price change for a one percentage point change in yield. A bond with a modified duration of 7 would be expected to rise approximately 7 percent if yields fell by one percentage point, or fall by the same amount if yields rose.</p>
<p>Convexity refines this estimate. Duration assumes a linear relationship between price and yield, but the true relationship is curved. Convexity measures the degree of that curvature. For large changes in yield, the duration-only estimate becomes inaccurate, and convexity must be added to the calculation.</p>
<p><span class="math display">\[
\%\Delta P \approx -D_{\text{mod}} \Delta y + \frac{1}{2} C (\Delta y)^2
\]</span></p>
<p>Where <span class="math inline">\(D_{\text{mod}}\)</span> is the modified duration, <span class="math inline">\(C\)</span> is the convexity, and <span class="math inline">\(\Delta y\)</span> is the change in yield. Convexity is always positive for standard bonds, meaning that a bond’s price rises more when yields fall than it declines when yields rise by the same amount. This asymmetry is valuable. All else equal, investors prefer bonds with higher convexity.</p>
<p>For corporate bonds and sovereign bonds of less creditworthy issuers, credit analysis joins interest rate analysis. The framework rests on the traditional Four Cs of credit. Capacity refers to the issuer’s ability to generate sufficient cash flow to meet its obligations. It is assessed through financial ratios—interest coverage, debt to EBITDA, free cash flow to debt—and through an understanding of the issuer’s business model and competitive position. Collateral refers to the assets available to secure the debt in the event of default. Secured bonds backed by specific assets offer greater recovery than unsecured bonds that rely only on the general credit of the issuer.</p>
<p>Covenants are the contractual protections embedded in the bond agreement. They may restrict the issuer from taking on additional debt, paying dividends, or selling assets without creditor consent. Strong covenants protect bondholders. Weak covenants leave them exposed. Character refers to the willingness of management to honor its obligations, a qualitative assessment based on the issuer’s track record, its communication with creditors, and the alignment of management’s incentives with those of bondholders.</p>
<p>Spread analysis evaluates whether a bond offers adequate compensation for the risks identified through the Four Cs. The credit spread is the difference between the bond’s yield and the yield of a comparable government bond. It reflects expected default losses and a risk premium for bearing uncertainty around those losses. A bond trading at a spread wider than its peers, after accounting for differences in credit quality, duration, and liquidity, may be cheap. A bond trading at a narrower spread may be rich.</p>
<p>Spread analysis often begins with the benchmark curve, typically the government bond yield curve for the currency in which the bond is denominated. A corporate bond’s yield is decomposed into the risk-free rate at the relevant maturity plus a spread. That spread can be further decomposed into the expected loss component and the risk premium component. The analyst judges whether the spread is sufficient given the credit profile of the issuer and the prevailing level of spreads in the market. Spreads that are tight by historical standards suggest that investors are being poorly compensated for credit risk. Spreads that are wide suggest attractive compensation, though they may also signal elevated default risk that justifies the wider spread.</p>
<p>The statement analysis techniques developed for equities apply, with modifications, to corporate credit. The debt-to-equity ratio of 774.42 in the worked example would be assessed differently for a corporate bond investor than for an equity investor. The bondholder cares less about upside earnings growth and more about the stability of cash flows and the adequacy of assets to cover obligations in a stress scenario. A company with high leverage but stable, predictable cash flows may be a better credit than a company with low leverage and volatile earnings. The Four Cs framework captures these distinctions. Capacity is the primary concern. Character is the secondary concern. Collateral and covenants provide the backstop.</p>
<p>Fixed income analysis, whether applied to government bonds or corporate credit, is fundamentally an exercise in assessing risk and return at the security level. The analysis does not ask whether bonds as an asset class belong in the portfolio—that is the strategic allocation decision. It asks which specific bonds best fulfill the role that the strategic allocation has assigned to them. For a government bond allocation designed to provide safety and liquidity, the emphasis falls on duration management and the issuer’s creditworthiness. For a corporate bond allocation designed to enhance yield, the emphasis shifts to credit selection and spread analysis. The tools described in this section serve both purposes, adapted to the specific objectives of each allocation.</p>
</section>
<section id="analyzing-alternative-assets-commodities-and-cryptocurrencies" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="analyzing-alternative-assets-commodities-and-cryptocurrencies"><span class="header-section-number">10.5</span> Analyzing Alternative Assets: Commodities and Cryptocurrencies</h2>
<p>Equities generate cash flows. Bonds pay coupons. Commodities and cryptocurrencies do neither. They are alternative assets, distinct in structure and in the analytical frameworks required to evaluate them. Their inclusion in a portfolio is not mandatory. The Schmidt-Miller IPS excludes cryptocurrencies and limits commodities to a tactical role. But the analyst must understand these assets, if only to explain why they are excluded.</p>
<p>Commodity analysis begins with supply and demand. The price of oil, copper, or wheat is determined by the balance between production and consumption. When demand outstrips supply, prices rise. When supply exceeds demand, prices fall. The analyst tracks inventory levels, production forecasts, and consumption trends to gauge the direction of that balance. Geopolitical shocks—a pipeline disruption, a trade embargo, a war in a producing region—can shift supply abruptly. Weather can destroy crops. Technological change can unlock new sources of supply or reduce demand for existing ones.</p>
<p>The cost of carry links spot prices to futures prices. It includes storage costs, insurance, and the interest cost of financing the commodity position. When the futures price exceeds the spot price, the market is in contango. When the spot price exceeds the futures price, it is in backwardation. The shape of the futures curve determines the roll yield, the return earned by rolling a futures contract forward as it approaches expiration.</p>
<p>In a contango market, rolling a long position incurs a cost. The expiring contract is sold at a lower price, and the new contract is purchased at a higher one. The roll yield is negative. In a backwardated market, the roll yield is positive. The expiring contract is sold at a higher price than the new contract is purchased. Over time, the roll yield can dominate the total return from commodity exposure, outweighing the change in the spot price. The commodity analyst must understand the futures curve. Ignoring it is not an option.</p>
<p>Cryptocurrency analysis operates on entirely different principles. There are no cash flows, no physical supply constraints in the traditional sense, and no central authority managing supply. The analysis focuses on network fundamentals. Bitcoin and Ethereum are networks, and their value depends on adoption, usage, and security.</p>
<p>Metcalfe’s Law provides a framework. It states that the value of a network is proportional to the square of the number of its users. More users create more connections, and more connections create more value. Active addresses on the blockchain serve as a proxy for users. Transaction volumes and frequency provide additional metrics. A network with growing adoption and increasing usage has a plausible claim to increasing value. A network with stagnant or declining usage faces headwinds.</p>
<p>Hash rate measures the computational power securing proof-of-work networks like Bitcoin. A higher hash rate indicates greater security, as more computing power would be required to attack the network. It also reflects miner confidence, as miners invest in equipment and electricity based on their expectation of future prices. Declining hash rates can signal miner capitulation and network stress.</p>
<p>Tokenomics refers to the economic design of a cryptocurrency. Supply is governed by protocol rules, not by central bank committees. Bitcoin’s supply is capped at twenty-one million coins, with the rate of new issuance halving every four years. This halving cycle creates predictable supply shocks that have historically preceded price appreciation. Other cryptocurrencies employ different mechanisms: burning tokens to reduce supply, distributing staking rewards to incentivize network participation, or adjusting issuance algorithmically based on network conditions. The analyst must understand the rules governing supply. They are as fundamental to cryptocurrency valuation as earnings growth is to equity valuation.</p>
<p>On-chain analysis exploits the transparency of public blockchains. Every transaction is recorded on a distributed ledger, visible to anyone. Analysts track the movements of large holders, known as whales, whose transactions can signal impending selling pressure or accumulation. Exchange flows—the movement of coins between wallets and exchanges—provide insight into investor behavior. Large inflows to exchanges suggest that holders are preparing to sell. Large outflows suggest accumulation and a preference for self-custody. These signals are noisy, but they provide a window into market dynamics that is unavailable in traditional asset classes.</p>
<p>The inclusion of alternative assets in a portfolio is a strategic decision. The analytical frameworks described here inform that decision. For the Schmidt-Miller family, commodities may play a limited tactical role, as discussed in Chapter 8. Cryptocurrencies are excluded from the policy portfolio due to their volatility, their uncertain regulatory status, and their incompatibility with Klaus’s loss aversion. The analyst understands them regardless, because understanding what is excluded is as important as understanding what is included. The boundaries of the permissible investment universe are not arbitrary. They are the product of analysis, grounded in the characteristics of the assets and the circumstances of the client.</p>
</section>
<section id="security-selection-in-a-portfolio-context" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="security-selection-in-a-portfolio-context"><span class="header-section-number">10.6</span> Security Selection in a Portfolio Context</h2>
<p>Security analysis ends with a list of candidates. Portfolio construction begins with that list and asks a different set of questions. Not every undervalued stock belongs in the portfolio. Not every attractively priced bond is suitable. The transition from analysis to selection requires weighing conviction against concentration, opportunity against capacity.</p>
<p>Active share measures how much a portfolio differs from its benchmark. It is calculated as the sum of absolute active weights divided by two:</p>
<p><span class="math display">\[
\text{Active Share} = \frac{1}{2} \sum_{i=1}^{N} |w_{p,i} - w_{b,i}|
\]</span></p>
<p>Where <span class="math inline">\(w_{p,i}\)</span> is the portfolio weight of security <span class="math inline">\(i\)</span> and <span class="math inline">\(w_{b,i}\)</span> is its weight in the benchmark. An active share of zero means the portfolio mirrors the benchmark exactly. An active share of one hundred percent means it holds nothing in common with the benchmark. High active share implies high conviction. The manager is betting that the selected securities will outperform the index by a margin sufficient to justify the deviation.</p>
<p>Active share alone does not capture risk. Two portfolios can have identical active shares but very different risk profiles. One might be diversified across many sectors with modest stock-specific tilts. The other might be concentrated in a single sector with large stock-specific bets. The tracking error, introduced in Chapter 9, captures the risk dimension:</p>
<p><span class="math display">\[
\sigma_{\text{active}} = \sqrt{w_a^T \Sigma w_a}
\]</span></p>
<p>Where <span class="math inline">\(w_a\)</span> is the vector of active weights and <span class="math inline">\(\Sigma\)</span> is the covariance matrix of security returns. A high active share combined with low tracking error suggests many small, uncorrelated bets. A high active share with high tracking error suggests a few concentrated bets. The desired combination depends on the manager’s skill and the breadth of opportunities, as the Fundamental Law of Active Management established:</p>
<p><span class="math display">\[
IR = IC \times \sqrt{BR}
\]</span></p>
<p>Conviction and concentration travel together. A manager who identifies ten stocks as deeply undervalued and allocates capital equally among them is expressing higher conviction—and accepting greater concentration risk—than one who holds two hundred names with modest active weights. The former portfolio will deviate significantly from the benchmark. If the analysis is correct, the returns will be exceptional. If the analysis is wrong, the losses will be equally so.</p>
<p>The trade-off can be formalized through the expected excess return and its variance. Suppose the manager has an expected alpha of <span class="math inline">\(\alpha_i\)</span> for each security, with an expected tracking error of <span class="math inline">\(\sigma_{\alpha,i}\)</span>. The portfolio’s expected alpha is the weighted sum of individual alphas. Its variance depends on the covariance of those alphas and the number of independent positions:</p>
<p><span class="math display">\[
\sigma_{\alpha,p}^2 = \sum_{i=1}^{N} w_{a,i}^2 \sigma_{\alpha,i}^2 + \sum_{i=1}^{N} \sum_{j \neq i} w_{a,i} w_{a,j} \rho_{ij} \sigma_{\alpha,i} \sigma_{\alpha,j}
\]</span></p>
<p>Greater diversification reduces the portfolio-level tracking error, but at the cost of diluting the expected alpha per unit of active risk. The optimal number of positions balances these forces.</p>
<p>Closet indexing arises when active share is low and tracking error is minimal. The manager charges active fees but delivers benchmark-like returns. The investor pays for conviction but receives a portfolio that hugs the index. This failure mode has a mathematical footprint. The active share is below sixty percent. The tracking error is below two percent. The R-squared with the benchmark exceeds 0.95. These metrics, taken together, are a diagnostic for a portfolio that is active in name only.</p>
<p>Capacity and liquidity impose further constraints. Every security has a maximum position size beyond which trading becomes difficult. The market impact of a trade can be modeled as a function of the trade size relative to average daily volume:</p>
<p><span class="math display">\[
\text{Impact Cost} \approx \sigma_{\text{daily}} \times \sqrt{\frac{Q}{\text{ADV}}}
\]</span></p>
<p>Where <span class="math inline">\(Q\)</span> is the quantity traded and <span class="math inline">\(ADV\)</span> is the average daily volume. The larger the trade relative to normal market activity, the greater the price movement against the trader. A small-cap stock with limited volume cannot absorb a large order without significant impact. The manager who identifies an opportunity in such a stock must either accept a smaller position than conviction warrants or incur higher costs that reduce the net alpha.</p>
<p>Liquidity constraints are particularly binding for large portfolios. The Schmidt-Miller long-term portfolio, at over €18 million, is not large by institutional standards, but position sizing still requires attention. An allocation of 2 percent is €360,000. In a liquid large-cap stock, this is easily absorbed. In a smaller company, it may represent several days of average volume. The resulting implementation shortfall, modeled in Chapter 9, would consume a material portion of the expected excess return.</p>
<p>Security selection is the point at which analysis meets action. Candidates are identified through fundamental or quantitative analysis. Their contribution to the portfolio’s expected excess return and tracking error is evaluated. Positions are sized to reflect conviction while respecting concentration limits, liquidity constraints, and the risk budget. The process is iterative and quantitative, blending judgment with the discipline that the mathematical framework imposes. The final portfolio is not simply a collection of good ideas. It is a deliberate combination of securities, each chosen because its expected contribution to alpha exceeds its marginal contribution to risk.</p>
</section>
<section id="case-study-selecting-the-schmidt-miller-securities" class="level2" data-number="10.7">
<h2 data-number="10.7" class="anchored" data-anchor-id="case-study-selecting-the-schmidt-miller-securities"><span class="header-section-number">10.7</span> Case Study: Selecting the Schmidt-Miller Securities</h2>
<p>The strategic asset allocation from Chapter 7 established the policy weights. The long-term portfolio holds 35 percent global equities, 15 percent Swiss equities, 30 percent corporate bonds, and 20 percent government bonds. These weights are abstract. They must be translated into specific securities, selected according to the analytical frameworks developed in this chapter. The challenge is not simply to find a fund or a bond that fits each category. It is to select securities that serve the family’s distinct circumstances—Klaus’s loss aversion, Elke’s emotional attachment to her inheritance, and the need for reliable income.</p>
<p>The equity allocation requires two distinct solutions. The global equity component, at 35 percent of the long-term portfolio, demands broad diversification and low cost. A global quality ETF, screening for companies with high profitability, low leverage, and stable earnings, serves this purpose. Quality companies tend to decline less in bear markets, a characteristic that aligns with Klaus’s binding constraint on downside risk. The screening criteria include return on equity above 15 percent, debt-to-equity below 50 percent, and positive earnings growth over the past five years. Companies that fail these screens are excluded, regardless of their valuation. The result is a portfolio tilted toward businesses with durable competitive advantages and conservative financial management.</p>
<p>The Swiss equity component presents a more complex problem. Elke already holds €2.5 million in inherited Swiss equities with a low cost basis. Selling these positions outright would trigger a 20 percent capital gains tax, consuming €500,000 of value. The solution is to treat the inherited holdings as a Swiss equity allocation and supplement them with a Swiss value fund that tilts toward high-dividend, low-volatility stocks. The inherited stocks are concentrated in a few names—likely the large-cap industrials and financials that dominated the Swiss market a generation ago. The value fund adds diversification across sectors and introduces a systematic, factor-based approach that the inherited portfolio lacks.</p>
<p>The inherited holdings are mapped against the fund’s holdings. Overlapping positions are retained in the inherited account to avoid realizing gains. Non-overlapping positions are added through the fund. Over time, as the inherited stocks appreciate further or as tax-loss harvesting opportunities arise, the portfolio migrates toward the factor-based fund. The transition is gradual. Elke’s emotional attachment is respected. No stock is sold without her understanding and consent. But the direction of travel is clear: from a concentrated, legacy portfolio to a diversified, systematically managed one.</p>
<p>The financials company from the worked example illustrates the type of security the analyst would assess in this context. It is a European financials stock with a recovering earnings profile, a declining debt-to-equity ratio, and a low P/E relative to its own history. It could belong in either the global equity sleeve or the Swiss equity sleeve, depending on its domicile. If it passes the quality screens—ROE above 15 percent, debt-to-equity below the sector norm, positive earnings growth—it becomes a candidate. If its factor profile (negative momentum, negative profitability loading) suggests that the recovery has not been recognized by the market, the analyst may see an opportunity. If the negative profitability loading reflects genuine concerns about the sustainability of the recovery, the analyst may pass. The decision rests on the fundamental analysis, not on the factor betas alone.</p>
<p>Fixed income selection serves a different purpose. The government bond allocation is not designed to generate return. It is designed to immunize the family’s commitment to €160,000 in annual retirement spending. The approach is liability-driven. A ladder of high-quality CHF-denominated bonds is constructed, with maturities staggered to match the expected withdrawals over the next ten years. Each bond is held to maturity, eliminating interest rate risk for that portion of the portfolio. The credit quality is impeccable. Swiss Confederation bonds and obligations of Swiss cantons with the highest credit ratings form the core.</p>
<p>The yield on these bonds is low, consistent with the capital market assumptions from Chapter 6. A ten-year Swiss government bond yields approximately 1.2 percent. The ladder produces an average yield slightly higher, reflecting the inclusion of slightly longer maturities and the modest credit spread of cantonal bonds. The expected return is not exciting. It is not meant to be. These bonds exist so that Klaus can sleep at night, knowing that the family’s spending needs are met regardless of what happens in equity markets.</p>
<p>The corporate bond allocation seeks a higher yield while maintaining investment-grade quality. The selection criteria emphasize issuer diversification, duration management, and credit quality. Bonds are selected from a universe of Swiss and European corporate issuers with ratings of BBB or higher. The average duration is held below five years to limit interest rate sensitivity. The portfolio avoids sectors with elevated ESG risk—thermal coal, controversial weapons, tobacco—not as an ethical screen but because these sectors face uncertain regulatory futures that could impair credit quality.</p>
<p>The question of commodities or gold arises from the tactical discussion in Chapter 8. The strategic allocation does not include commodities. But the Investment Clock framework and the stagflation scenario suggest that a small allocation to an inflation-hedging asset may reduce shortfall risk without materially increasing volatility. Gold, rather than a broad commodity ETF, is the preferred vehicle. Gold’s negative correlation with real interest rates and its role as a safe haven during periods of market stress complement the portfolio’s existing exposures. A 2 percent allocation, funded from the government bond allocation, adds diversification without consuming significant tracking error.</p>
<p>Bitcoin is considered and rejected. The network fundamentals are compelling. Metcalfe’s Law suggests that value scales with adoption. On-chain metrics show growing usage. But volatility exceeds 60 percent per year. Drawdowns of 80 percent or more are common. For a family whose binding constraint is Klaus’s loss aversion, an asset with this risk profile is incompatible with the IPS. The analysis does not dismiss Bitcoin as worthless. It dismisses it as unsuitable for this particular client.</p>
<p>The final portfolio of securities reflects the layered logic of the entire investment process. The strategic allocation provides the architecture. The tactical analysis provides the tilt. Security selection provides the materials. Each layer is consistent with the layer above it. Each security is chosen not because it is the best in isolation but because it contributes something the portfolio needs—and because it does so without violating the constraints that define the Schmidt-Miller family’s relationship with their wealth.</p>
</section>
<section id="security-analysis-in-imag" class="level2" data-number="10.8">
<h2 data-number="10.8" class="anchored" data-anchor-id="security-analysis-in-imag"><span class="header-section-number">10.8</span> Security Analysis in IMAG</h2>
<p>The framework developed in this chapter is applied directly in the IMAG simulation. The strategic allocation established our policy weights. The tactical allocation expressed our near-term views. Security analysis is the final step: selecting the specific instruments that will populate each market segment. This is where the Brinson-Fachler selection effect is determined. A positive selection effect means the securities we chose within each asset class outperformed their benchmarks. Security analysis is the discipline that seeks to make that happen.</p>
<section id="from-tactical-weights-to-asset-level-positions" class="level3" data-number="10.8.1">
<h3 data-number="10.8.1" class="anchored" data-anchor-id="from-tactical-weights-to-asset-level-positions"><span class="header-section-number">10.8.1</span> From Tactical Weights to Asset-Level Positions</h3>
<p>The simulation provides two paths for translating tactical weights into specific positions. When asset-level automation is enabled, the system distributes the tactical allocation across individual assets automatically. Equities use market value weights by default. Other segments use equal weighting. This reflects the principle that tactical allocation is primarily about asset class and currency decisions. If we hold no specific views about individual securities, the automation provides a low-cost, diversified implementation.</p>
<p>When we disable the automation, we take direct control of asset-level decisions on the Markets page. This is appropriate when we hold security-specific views grounded in the analysis from this chapter. If our fundamental analysis suggests that a particular sector or factor tilt will add value, we can overweight those securities relative to their market weights. If our credit analysis identifies a corporate bond that offers an attractive spread relative to its default risk, we can add it to the fixed income allocation.</p>
<p>The cost of this granularity is the risk we examined in the chapter. Every additional security-level decision is an opportunity to be wrong. The Fundamental Law reminds us that breadth helps only if we have genuine skill. If our security-level forecasts have no predictive power, adding more bets increases noise and trading costs without improving expected returns. The automation exists for a reason. For most market segments, the automated implementation is sufficient. We reserve active security selection for cases where we have a clear, analytically grounded thesis.</p>
</section>
<section id="evaluating-security-selection" class="level3" data-number="10.8.2">
<h3 data-number="10.8.2" class="anchored" data-anchor-id="evaluating-security-selection"><span class="header-section-number">10.8.2</span> Evaluating Security Selection</h3>
<p>The Analyst page closes the loop between security selection and performance evaluation. After each round, we can decompose our returns to understand which decisions contributed and which detracted. The attribution analysis covers asset class, currency, industry, maturity, and factor exposures. The selection effect isolates the contribution of our security choices. If we selected a corporate bond fund that outperformed the corporate bond benchmark, the attribution will show a positive selection effect for that segment. If we tilted the equity allocation toward value stocks and value outperformed growth, the factor attribution will capture that contribution.</p>
<p>The strategic allocation analysis on the same page assesses how well our portfolio meets the needs of each client type. If our security selection caused the portfolio to deviate from the intended factor exposures or risk characteristics, the gap will be visible here. This is the final check on the entire investment process. Client analysis established the objectives and constraints. Strategic allocation translated them into policy weights. Tactical allocation expressed our market views. Security selection populated the portfolio with specific instruments. The strategic allocation analysis confirms whether the chain held.</p>
</section>
<section id="applying-the-chapter-framework" class="level3" data-number="10.8.3">
<h3 data-number="10.8.3" class="anchored" data-anchor-id="applying-the-chapter-framework"><span class="header-section-number">10.8.3</span> Applying the Chapter Framework</h3>
<p>The simulation rewards the same discipline we developed for the Schmidt-Miller portfolio. Security selection begins with the client. Klaus’s loss aversion drove us toward quality equities with lower downside capture and government bonds held to maturity. Elke’s endowment bias required us to integrate her inherited holdings rather than liquidate them. These constraints are not obstacles. They define what a suitable security looks like.</p>
<p>The analytical frameworks from this chapter provide the tools. Fundamental analysis informs equity selection. Credit analysis informs bond selection. Factor analysis ensures that the portfolio’s exposures are intentional rather than accidental. ESG analysis, applied as a quality overlay, helps identify risks that financial statements may not yet reflect. Each framework serves the same objective: selecting securities that serve the client’s goals without violating the client’s constraints.</p>
<p>The automation tools streamline the process without eliminating the need for judgment. The default settings provide a reasonable baseline. Deviating from them requires a reason grounded in analysis. Start from the benchmark. Deviate only when the data supports it. Respect the constraints. Evaluate the results honestly. The simulation provides the environment. The framework provides the method. The quality of the decisions determines the outcome.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation column-body">
  <div class="nav-page nav-page-previous">
      <a href="./09_Tactical_Asset_Allocation.html" class="pagination-link" aria-label="Tactical Asset Allocation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Tactical Asset Allocation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./11_Portfolio_Implementation.html" class="pagination-link" aria-label="Portfolio Implementation">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Portfolio Implementation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 <div class="imag-footer-wrap"><div class="imag-footer-logos"><img src="../assets/logos/uli.jpg" alt="University of Liechtenstein"><img src="../assets/logos/unibz.jpg" alt="unibz"><img src="../assets/logos/cesim.png" alt="Cesim"><img src="../assets/logos/erasmus.jpg" alt="Erasmus+"></div><p>© 2025 Investment Management Game (IMAG). All rights reserved.</p><p>Supported by <a href="https://erasmus-plus.ec.europa.eu/projects/search/details/2022-1-LI01-KA220-HED-000085536" target="_blank">Erasmus+</a> and partner institutions.</p></div>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>