<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Tactical Asset Allocation – IMAG Teaching Materials</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./10_Security_Analysis.html" rel="next">
<link href="./08_Tactical_Financial_Analysis.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9ccdb83cb3135e29ca75cb95b795602d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <a class="flex-grow-1 no-decor" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
          <h1 class="quarto-secondary-nav-title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Tactical Asset Allocation</span></h1>
        </a>     
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">IMAG Teaching Materials</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">IMAG Teaching Materials</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_Introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_Asset_Classes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Asset Classes, Currencies and Instruments</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_Sustainable_Investing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Sustainable Investing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_Client_Analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Client Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_Investment_Policy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Investment Policy</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_Strategic_Fiancial_Analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Strategic Financial Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_Strategic_Asset_Allocation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Strategic Asset Allocation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_Tactical_Financial_Analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Tactical Financial Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_Tactical_Asset_Allocation.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Tactical Asset Allocation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_Security_Analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Security Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_Portfolio_Implementation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Portfolio Implementation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12_Portfolio_Analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Performance Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13_Feedback_Loop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Feedback Loop</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">9.1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#concept-of-tactical-asset-allocation" id="toc-concept-of-tactical-asset-allocation" class="nav-link" data-scroll-target="#concept-of-tactical-asset-allocation"><span class="header-section-number">9.1.1</span> Concept of Tactical Asset Allocation</a></li>
  <li><a href="#dual-objectives-of-tactical-asset-allocation" id="toc-dual-objectives-of-tactical-asset-allocation" class="nav-link" data-scroll-target="#dual-objectives-of-tactical-asset-allocation"><span class="header-section-number">9.1.2</span> Dual Objectives of Tactical Asset Allocation</a></li>
  <li><a href="#integration-with-overall-investment-strategy" id="toc-integration-with-overall-investment-strategy" class="nav-link" data-scroll-target="#integration-with-overall-investment-strategy"><span class="header-section-number">9.1.3</span> Integration with Overall Investment Strategy</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">9.1.4</span> Conclusion</a></li>
  </ul></li>
  <li><a href="#understanding-market-signals-for-tactical-asset-allocation" id="toc-understanding-market-signals-for-tactical-asset-allocation" class="nav-link" data-scroll-target="#understanding-market-signals-for-tactical-asset-allocation"><span class="header-section-number">9.2</span> Understanding Market Signals for Tactical Asset Allocation</a>
  <ul class="collapse">
  <li><a href="#identifying-key-market-signals-and-indicators" id="toc-identifying-key-market-signals-and-indicators" class="nav-link" data-scroll-target="#identifying-key-market-signals-and-indicators"><span class="header-section-number">9.2.1</span> Identifying Key Market Signals and Indicators</a></li>
  <li><a href="#the-importance-of-timing-in-taa" id="toc-the-importance-of-timing-in-taa" class="nav-link" data-scroll-target="#the-importance-of-timing-in-taa"><span class="header-section-number">9.2.2</span> The Importance of Timing in TAA</a></li>
  <li><a href="#conclusion-1" id="toc-conclusion-1" class="nav-link" data-scroll-target="#conclusion-1"><span class="header-section-number">9.2.3</span> Conclusion</a></li>
  </ul></li>
  <li><a href="#implementing-tactical-asset-allocation-in-the-portfolio" id="toc-implementing-tactical-asset-allocation-in-the-portfolio" class="nav-link" data-scroll-target="#implementing-tactical-asset-allocation-in-the-portfolio"><span class="header-section-number">9.3</span> Implementing Tactical Asset Allocation in the Portfolio</a>
  <ul class="collapse">
  <li><a href="#asset-class-level-adjustments" id="toc-asset-class-level-adjustments" class="nav-link" data-scroll-target="#asset-class-level-adjustments"><span class="header-section-number">9.3.1</span> Asset Class Level Adjustments</a></li>
  <li><a href="#geographic-allocation-adjustments" id="toc-geographic-allocation-adjustments" class="nav-link" data-scroll-target="#geographic-allocation-adjustments"><span class="header-section-number">9.3.2</span> Geographic Allocation Adjustments</a></li>
  <li><a href="#currency-considerations-in-taa" id="toc-currency-considerations-in-taa" class="nav-link" data-scroll-target="#currency-considerations-in-taa"><span class="header-section-number">9.3.3</span> Currency Considerations in TAA</a></li>
  <li><a href="#sector-and-security-selection" id="toc-sector-and-security-selection" class="nav-link" data-scroll-target="#sector-and-security-selection"><span class="header-section-number">9.3.4</span> Sector and Security Selection</a></li>
  <li><a href="#conclusion-2" id="toc-conclusion-2" class="nav-link" data-scroll-target="#conclusion-2"><span class="header-section-number">9.3.5</span> Conclusion</a></li>
  </ul></li>
  <li><a href="#measuring-and-managing-tracking-error" id="toc-measuring-and-managing-tracking-error" class="nav-link" data-scroll-target="#measuring-and-managing-tracking-error"><span class="header-section-number">9.4</span> Measuring and Managing Tracking Error</a>
  <ul class="collapse">
  <li><a href="#definition-and-importance-of-tracking-error" id="toc-definition-and-importance-of-tracking-error" class="nav-link" data-scroll-target="#definition-and-importance-of-tracking-error"><span class="header-section-number">9.4.1</span> Definition and Importance of Tracking Error</a></li>
  <li><a href="#techniques-for-managing-and-controlling-tracking-error" id="toc-techniques-for-managing-and-controlling-tracking-error" class="nav-link" data-scroll-target="#techniques-for-managing-and-controlling-tracking-error"><span class="header-section-number">9.4.2</span> Techniques for Managing and Controlling Tracking Error</a></li>
  <li><a href="#conclusion-3" id="toc-conclusion-3" class="nav-link" data-scroll-target="#conclusion-3"><span class="header-section-number">9.4.3</span> Conclusion</a></li>
  </ul></li>
  <li><a href="#costs-and-benefits-of-tactical-moves" id="toc-costs-and-benefits-of-tactical-moves" class="nav-link" data-scroll-target="#costs-and-benefits-of-tactical-moves"><span class="header-section-number">9.5</span> Costs and Benefits of Tactical Moves</a>
  <ul class="collapse">
  <li><a href="#analyzing-the-costs-associated-with-taa" id="toc-analyzing-the-costs-associated-with-taa" class="nav-link" data-scroll-target="#analyzing-the-costs-associated-with-taa"><span class="header-section-number">9.5.1</span> Analyzing the Costs Associated with TAA</a></li>
  <li><a href="#weighing-benefits-against-costs-and-risks" id="toc-weighing-benefits-against-costs-and-risks" class="nav-link" data-scroll-target="#weighing-benefits-against-costs-and-risks"><span class="header-section-number">9.5.2</span> Weighing Benefits Against Costs and Risks</a></li>
  <li><a href="#conclusion-4" id="toc-conclusion-4" class="nav-link" data-scroll-target="#conclusion-4"><span class="header-section-number">9.5.3</span> Conclusion</a></li>
  </ul></li>
  <li><a href="#sustainability-considerations-in-tactical-asset-allocation" id="toc-sustainability-considerations-in-tactical-asset-allocation" class="nav-link" data-scroll-target="#sustainability-considerations-in-tactical-asset-allocation"><span class="header-section-number">9.6</span> Sustainability Considerations in Tactical Asset Allocation</a>
  <ul class="collapse">
  <li><a href="#incorporating-short-term-sustainability-trends-and-esg-factor-shifts" id="toc-incorporating-short-term-sustainability-trends-and-esg-factor-shifts" class="nav-link" data-scroll-target="#incorporating-short-term-sustainability-trends-and-esg-factor-shifts"><span class="header-section-number">9.6.1</span> Incorporating Short-term Sustainability Trends and ESG Factor Shifts</a></li>
  <li><a href="#evaluating-the-impact-of-sudden-sustainability-related-news" id="toc-evaluating-the-impact-of-sudden-sustainability-related-news" class="nav-link" data-scroll-target="#evaluating-the-impact-of-sudden-sustainability-related-news"><span class="header-section-number">9.6.2</span> Evaluating the Impact of Sudden Sustainability-Related News</a></li>
  <li><a href="#conclusion-5" id="toc-conclusion-5" class="nav-link" data-scroll-target="#conclusion-5"><span class="header-section-number">9.6.3</span> Conclusion</a></li>
  </ul></li>
  <li><a href="#case-studies-in-tactical-asset-allocation" id="toc-case-studies-in-tactical-asset-allocation" class="nav-link" data-scroll-target="#case-studies-in-tactical-asset-allocation"><span class="header-section-number">9.7</span> Case Studies in Tactical Asset Allocation</a>
  <ul class="collapse">
  <li><a href="#case-study-1-successful-taa-decision-during-the-covid-19-market-volatility" id="toc-case-study-1-successful-taa-decision-during-the-covid-19-market-volatility" class="nav-link" data-scroll-target="#case-study-1-successful-taa-decision-during-the-covid-19-market-volatility"><span class="header-section-number">9.7.1</span> Case Study 1: Successful TAA Decision During the COVID-19 Market Volatility</a></li>
  <li><a href="#case-study-2-unsuccessful-taa-decision-during-the-2008-financial-crisis" id="toc-case-study-2-unsuccessful-taa-decision-during-the-2008-financial-crisis" class="nav-link" data-scroll-target="#case-study-2-unsuccessful-taa-decision-during-the-2008-financial-crisis"><span class="header-section-number">9.7.2</span> Case Study 2: Unsuccessful TAA Decision During the 2008 Financial Crisis</a></li>
  </ul></li>
  <li><a href="#conclusion-the-strategic-importance-of-tactical-asset-allocation" id="toc-conclusion-the-strategic-importance-of-tactical-asset-allocation" class="nav-link" data-scroll-target="#conclusion-the-strategic-importance-of-tactical-asset-allocation"><span class="header-section-number">9.8</span> Conclusion: The Strategic Importance of Tactical Asset Allocation</a>
  <ul class="collapse">
  <li><a href="#key-aspects-of-taa" id="toc-key-aspects-of-taa" class="nav-link" data-scroll-target="#key-aspects-of-taa"><span class="header-section-number">9.8.1</span> Key Aspects of TAA:</a></li>
  <li><a href="#encouraging-disciplined-decision-making" id="toc-encouraging-disciplined-decision-making" class="nav-link" data-scroll-target="#encouraging-disciplined-decision-making"><span class="header-section-number">9.8.2</span> Encouraging Disciplined Decision-Making</a></li>
  </ul></li>
  <li><a href="#conclusion-6" id="toc-conclusion-6" class="nav-link" data-scroll-target="#conclusion-6"><span class="header-section-number">9.9</span> Conclusion</a></li>
  <li><a href="#black-litterman-model-and-active-portfolio-management" id="toc-black-litterman-model-and-active-portfolio-management" class="nav-link" data-scroll-target="#black-litterman-model-and-active-portfolio-management"><span class="header-section-number">9.10</span> Black-Litterman model and Active Portfolio Management</a>
  <ul class="collapse">
  <li><a href="#assumptions-and-inputs" id="toc-assumptions-and-inputs" class="nav-link" data-scroll-target="#assumptions-and-inputs"><span class="header-section-number">9.10.1</span> Assumptions and Inputs</a></li>
  <li><a href="#procedure" id="toc-procedure" class="nav-link" data-scroll-target="#procedure"><span class="header-section-number">9.10.2</span> Procedure</a></li>
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example"><span class="header-section-number">9.10.3</span> Example:</a></li>
  <li><a href="#active-management" id="toc-active-management" class="nav-link" data-scroll-target="#active-management"><span class="header-section-number">9.10.4</span> Active management</a></li>
  <li><a href="#example-1" id="toc-example-1" class="nav-link" data-scroll-target="#example-1"><span class="header-section-number">9.10.5</span> Example:</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Tactical Asset Allocation</span></h1>
</div>



<div class="quarto-title-meta column-body">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">9.1</span> Introduction</h2>
<p>Tactical Asset Allocation (TAA) represents a dynamic investment strategy aimed at enhancing portfolio returns and managing risk through short to medium-term adjustments to the asset mix. This chapter will explore the fundamentals of TAA, illustrating how it differs from and complements strategic asset allocation.</p>
<section id="concept-of-tactical-asset-allocation" class="level3" data-number="9.1.1">
<h3 data-number="9.1.1" class="anchored" data-anchor-id="concept-of-tactical-asset-allocation"><span class="header-section-number">9.1.1</span> Concept of Tactical Asset Allocation</h3>
<section id="definition-and-purpose" class="level4" data-number="9.1.1.1">
<h4 data-number="9.1.1.1" class="anchored" data-anchor-id="definition-and-purpose"><span class="header-section-number">9.1.1.1</span> Definition and Purpose:</h4>
<ul>
<li><strong>Tactical Asset Allocation (TAA):</strong> TAA involves temporarily deviating from the baseline strategic asset allocation to capitalize on short- to medium-term market opportunities or to avoid potential pitfalls. It adjusts the investment mix based on current market conditions, economic forecasts, or specific event-driven scenarios.</li>
<li><strong>Goal Orientation:</strong> The primary goal of TAA is to improve the portfolio’s risk-adjusted returns by taking advantage of perceived market inefficiencies or anticipated movements.</li>
</ul>
</section>
<section id="contrast-with-strategic-asset-allocation" class="level4" data-number="9.1.1.2">
<h4 data-number="9.1.1.2" class="anchored" data-anchor-id="contrast-with-strategic-asset-allocation"><span class="header-section-number">9.1.1.2</span> Contrast with Strategic Asset Allocation:</h4>
<ul>
<li><strong>Strategic Asset Allocation</strong> sets a long-term investment framework based on the investor’s risk tolerance, financial goals, and investment horizon. It is generally more static and changes primarily when there is a shift in these fundamental objectives.</li>
<li><strong>Tactical Asset Allocation</strong>, in contrast, is more flexible and responsive, allowing investors to adjust their exposure to various asset classes to respond to short-term market conditions without altering the underlying long-term investment strategy.</li>
</ul>
</section>
</section>
<section id="dual-objectives-of-tactical-asset-allocation" class="level3" data-number="9.1.2">
<h3 data-number="9.1.2" class="anchored" data-anchor-id="dual-objectives-of-tactical-asset-allocation"><span class="header-section-number">9.1.2</span> Dual Objectives of Tactical Asset Allocation</h3>
<section id="generating-alpha" class="level4" data-number="9.1.2.1">
<h4 data-number="9.1.2.1" class="anchored" data-anchor-id="generating-alpha"><span class="header-section-number">9.1.2.1</span> Generating Alpha:</h4>
<ul>
<li><strong>Exploiting Market Inefficiencies:</strong> Tactical moves aim to exploit temporary mispricings or to anticipate market moves before they are reflected in asset prices, potentially generating returns that exceed those of the broader market.</li>
<li><strong>Example Strategies:</strong> This could involve increasing allocation to a sector expected to outperform in the coming months based on leading economic indicators or reducing exposure to an asset class that might underperform due to foreseeable economic downturns.</li>
</ul>
</section>
<section id="managing-risk" class="level4" data-number="9.1.2.2">
<h4 data-number="9.1.2.2" class="anchored" data-anchor-id="managing-risk"><span class="header-section-number">9.1.2.2</span> Managing Risk:</h4>
<ul>
<li><strong>Mitigating Potential Losses:</strong> TAA can be used defensively to reduce exposure to riskier assets ahead of anticipated market downturns or increased volatility.</li>
<li><strong>Balancing the Portfolio:</strong> Tactical adjustments can help maintain the desired level of risk, especially when certain sectors or markets become overvalued or pose heightened risks.</li>
</ul>
</section>
</section>
<section id="integration-with-overall-investment-strategy" class="level3" data-number="9.1.3">
<h3 data-number="9.1.3" class="anchored" data-anchor-id="integration-with-overall-investment-strategy"><span class="header-section-number">9.1.3</span> Integration with Overall Investment Strategy</h3>
<ul>
<li><strong>Harmonizing with Strategic Goals:</strong> While TAA allows for temporary deviations, these should not conflict with the fundamental investment principles defined in the strategic asset allocation. Instead, they should complement the long-term goals, ensuring that any tactical moves are coherent with the overall investment objectives.</li>
<li><strong>Dynamic Adjustments:</strong> Implementing TAA requires continuous monitoring of market conditions and the ability to make swift decisions. The success of TAA hinges on the accuracy of market analysis and the timeliness of executing adjustments.</li>
</ul>
</section>
<section id="conclusion" class="level3" data-number="9.1.4">
<h3 data-number="9.1.4" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">9.1.4</span> Conclusion</h3>
<p>Tactical Asset Allocation is a sophisticated approach to portfolio management that requires a deep understanding of both market dynamics and the behavior of various asset classes. By effectively implementing TAA, investors can enhance potential returns and manage exposure to risks, making it a valuable tool for those seeking to optimize their investment outcomes in alignment with both their short-term perceptions and long-term financial goals. This chapter sets the foundation for understanding how to strategically employ TAA within the broader context of investment management.</p>
<div class="callout callout-style-default callout-note callout-titled" title="CFA Curriculum Alignment">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>CFA Curriculum Alignment
</div>
</div>
<div class="callout-body-container callout-body">
<p>The CFA curriculum emphasizes the importance of both strategic and tactical asset allocation in investment management. Understanding Tactical Asset Allocation is crucial for CFA candidates, as it covers how short- to medium-term adjustments to the asset allocation can be used to exploit market inefficiencies or respond to economic changes. The curriculum provides tools and frameworks for analyzing market conditions, which are essential for making informed tactical decisions. Mastery of these concepts is vital for aligning tactical moves with a portfolio’s strategic objectives, enhancing both risk management and return potential.</p>
</div>
</div>
</section>
</section>
<section id="understanding-market-signals-for-tactical-asset-allocation" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="understanding-market-signals-for-tactical-asset-allocation"><span class="header-section-number">9.2</span> Understanding Market Signals for Tactical Asset Allocation</h2>
<p>Effective Tactical Asset Allocation (TAA) hinges on the ability to interpret and act on key market signals. This subchapter delves into the types of signals that can trigger tactical shifts in asset allocation and discusses the critical aspect of timing—identifying optimal entry and exit points for tactical positions. Understanding these elements is crucial for capitalizing on opportunities and managing risks in a dynamic market environment.</p>
<section id="identifying-key-market-signals-and-indicators" class="level3" data-number="9.2.1">
<h3 data-number="9.2.1" class="anchored" data-anchor-id="identifying-key-market-signals-and-indicators"><span class="header-section-number">9.2.1</span> Identifying Key Market Signals and Indicators</h3>
<ul>
<li><strong>Economic Data Releases:</strong>
<ul>
<li><strong>Impact on Markets:</strong> Regularly scheduled economic reports such as GDP growth rates, unemployment data, inflation figures, and consumer spending can significantly influence market expectations and investor sentiment.</li>
<li><strong>How to Use:</strong> Positive surprises in economic data might prompt a tactical increase in exposure to cyclical sectors or equities in general, while negative data might lead to a shift towards more defensive assets like bonds or gold.</li>
</ul></li>
<li><strong>Interest Rate Movements:</strong>
<ul>
<li><strong>Central Bank Decisions:</strong> Decisions on interest rates by central banks are pivotal. A rate hike can decrease the attractiveness of equities and increase the appeal of fixed income securities, while rate cuts generally do the opposite.</li>
<li><strong>Market Response:</strong> Tactical adjustments may include shifting allocations between bonds and stocks, or between sectors that are differently impacted by interest rate changes, such as financials versus utilities.</li>
</ul></li>
<li><strong>Geopolitical Events:</strong>
<ul>
<li><strong>Types of Events:</strong> Elections, trade negotiations, conflicts, and other geopolitical developments can create volatility and drive market trends.</li>
<li><strong>Strategic Reactions:</strong> Tactical shifts might involve increasing investments in safe-haven assets like U.S. Treasuries or gold during times of high geopolitical tension, or capitalizing on the resolution of such tensions by investing in riskier assets.</li>
</ul></li>
</ul>
</section>
<section id="the-importance-of-timing-in-taa" class="level3" data-number="9.2.2">
<h3 data-number="9.2.2" class="anchored" data-anchor-id="the-importance-of-timing-in-taa"><span class="header-section-number">9.2.2</span> The Importance of Timing in TAA</h3>
<ul>
<li><strong>Recognizing Entry and Exit Points:</strong>
<ul>
<li><strong>Technical Analysis Tools:</strong> Use tools like moving averages, RSI (Relative Strength Index), and MACD (Moving Average Convergence Divergence) to identify potential turning points in the market. These tools can help pinpoint when a particular asset class or sector is entering or exiting favorable conditions.</li>
<li><strong>Sentiment Indicators:</strong> Monitor investor sentiment indicators, such as the VIX (Volatility Index), which can signal shifts in market dynamics and suggest timing for tactical adjustments.</li>
</ul></li>
<li><strong>Executing Tactical Decisions:</strong>
<ul>
<li><strong>Speed of Execution:</strong> In TAA, the speed at which adjustments are made can greatly impact their effectiveness. Rapid execution following the identification of a market signal is crucial, as delays can lead to missed opportunities or increased risks.</li>
<li><strong>Continuous Monitoring:</strong> Given the importance of timing, continuous monitoring of the market and regular re-assessment of positions are essential. This ensures that tactical allocations remain aligned with the latest market conditions and that exit strategies can be implemented effectively.</li>
</ul></li>
</ul>
</section>
<section id="conclusion-1" class="level3" data-number="9.2.3">
<h3 data-number="9.2.3" class="anchored" data-anchor-id="conclusion-1"><span class="header-section-number">9.2.3</span> Conclusion</h3>
<p>Understanding and acting on market signals are foundational aspects of Tactical Asset Allocation. By closely monitoring economic indicators, interest rate movements, and geopolitical events, and by mastering the art of timing, investors can make informed tactical decisions that enhance portfolio performance. The ability to swiftly and accurately interpret these signals allows for a proactive approach to investment management, adjusting allocations to both seize short-term opportunities and mitigate potential risks.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Practical Application – Effective Use of Market Signals in TAA">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Practical Application – Effective Use of Market Signals in TAA
</div>
</div>
<div class="callout-body-container callout-body">
<p>In practice, using market signals for Tactical Asset Allocation requires sophisticated market surveillance tools that can provide alerts on specific economic indicators, stock movements, or geopolitical events. For instance, setting up customized alerts for sudden changes in market volatility indices or interest rate announcements can help in making timely tactical adjustments. Portfolio managers should practice scenario analysis, using historical data to simulate potential market responses to similar events, which aids in developing a proactive rather than reactive TAA strategy.</p>
</div>
</div>
</section>
</section>
<section id="implementing-tactical-asset-allocation-in-the-portfolio" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="implementing-tactical-asset-allocation-in-the-portfolio"><span class="header-section-number">9.3</span> Implementing Tactical Asset Allocation in the Portfolio</h2>
<p>Tactical Asset Allocation (TAA) is a proactive investment strategy that adjusts portfolio compositions in response to short-term market conditions and opportunities. This subchapter explains how to effectively implement TAA across various dimensions of the portfolio, including asset classes, geographic regions, currency exposure, and specific sectors or securities.</p>
<section id="asset-class-level-adjustments" class="level3" data-number="9.3.1">
<h3 data-number="9.3.1" class="anchored" data-anchor-id="asset-class-level-adjustments"><span class="header-section-number">9.3.1</span> Asset Class Level Adjustments</h3>
<ul>
<li><strong>Overweighting and Underweighting:</strong>
<ul>
<li><strong>Criteria for Adjustment:</strong> Analyze current market trends, economic indicators, and future outlooks to decide whether to increase (overweight) or decrease (underweight) exposure to certain asset classes.</li>
<li><strong>Example Implementation:</strong> In a rising interest rate environment, tactically underweight bonds due to their inverse relationship with interest rates, and overweight sectors like banking which typically benefits from higher rates.</li>
</ul></li>
<li><strong>Flexibility and Responsiveness:</strong>
<ul>
<li><strong>Adaptive Portfolio Management:</strong> Maintain flexibility in your portfolio to quickly adapt to changing market conditions. This may involve using derivatives or exchange-traded funds (ETFs) to adjust exposures without the need to buy or sell large volumes of physical assets.</li>
</ul></li>
</ul>
</section>
<section id="geographic-allocation-adjustments" class="level3" data-number="9.3.2">
<h3 data-number="9.3.2" class="anchored" data-anchor-id="geographic-allocation-adjustments"><span class="header-section-number">9.3.2</span> Geographic Allocation Adjustments</h3>
<ul>
<li><strong>Evaluating Economic Outlooks:</strong>
<ul>
<li><strong>Regional Analysis:</strong> Assess economic and political stability, growth forecasts, and market potential of different regions and countries. Use this analysis to adjust geographic exposures in the portfolio.</li>
<li><strong>Dynamic Allocation:</strong> Increase exposure to emerging markets during periods of strong growth forecasts and stability, or shift towards more developed markets during times of global uncertainty or when emerging markets are expected to underperform.</li>
</ul></li>
</ul>
</section>
<section id="currency-considerations-in-taa" class="level3" data-number="9.3.3">
<h3 data-number="9.3.3" class="anchored" data-anchor-id="currency-considerations-in-taa"><span class="header-section-number">9.3.3</span> Currency Considerations in TAA</h3>
<ul>
<li><strong>Managing Currency Exposure:</strong>
<ul>
<li><strong>Currency Risk Management:</strong> Use currency forwards, futures, or options to hedge against unwanted currency risks or to take advantage of favorable currency movements.</li>
<li><strong>Tactical Currency Plays:</strong> Adjust the currency composition of the portfolio to benefit from predictions on currency strength or weakness based on interest rate differentials, economic policies, or geopolitical events.</li>
</ul></li>
</ul>
</section>
<section id="sector-and-security-selection" class="level3" data-number="9.3.4">
<h3 data-number="9.3.4" class="anchored" data-anchor-id="sector-and-security-selection"><span class="header-section-number">9.3.4</span> Sector and Security Selection</h3>
<ul>
<li><strong>Identifying Outperforming Sectors and Securities:</strong>
<ul>
<li><strong>Market Research and Analysis:</strong> Conduct detailed sector analysis to identify which sectors are likely to outperform based on current economic cycles, technological innovations, or regulatory changes.</li>
<li><strong>Security Selection:</strong> Within selected sectors, identify individual securities that show the potential for outperformance. Utilize fundamental and technical analysis to select stocks that are positioned to gain from current trends.</li>
</ul></li>
<li><strong>Real-Time Monitoring and Adjustment:</strong>
<ul>
<li><strong>Continuous Assessment:</strong> Keep a constant watch on the performance of chosen sectors and securities to ensure they continue to align with tactical objectives. Be prepared to make swift changes if the initial assumptions no longer hold true due to evolving market conditions.</li>
</ul></li>
</ul>
</section>
<section id="conclusion-2" class="level3" data-number="9.3.5">
<h3 data-number="9.3.5" class="anchored" data-anchor-id="conclusion-2"><span class="header-section-number">9.3.5</span> Conclusion</h3>
<p>Implementing Tactical Asset Allocation requires a comprehensive approach that considers multiple dimensions of the portfolio. By tactically adjusting asset classes, geographic and currency exposures, as well as selecting specific sectors and securities, investors can enhance returns and manage risks in alignment with short-term market movements. This strategy demands constant vigilance, flexibility, and a robust analytical framework to ensure that all tactical decisions are well-informed and timely.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Practical Application – Implementing Tactical Asset Allocation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Practical Application – Implementing Tactical Asset Allocation
</div>
</div>
<div class="callout-body-container callout-body">
<p>To effectively implement Tactical Asset Allocation, portfolio managers must utilize advanced market analysis tools and real-time data platforms. This involves setting up systems for continuous market monitoring and employing automated trading systems to quickly capitalize on short-term opportunities. Practically, this could mean using algorithmic trading to adjust positions or applying derivatives strategically to manage risks associated with rapid market movements. Regular training in the latest financial software and analytical tools is essential for maintaining an edge in tactical decision-making.</p>
</div>
</div>
</section>
</section>
<section id="measuring-and-managing-tracking-error" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="measuring-and-managing-tracking-error"><span class="header-section-number">9.4</span> Measuring and Managing Tracking Error</h2>
<p>Tracking error is a critical metric in the management of Tactical Asset Allocation (TAA), providing a quantitative measure of the deviation of portfolio returns from a benchmark. This subchapter defines tracking error, discusses its significance in evaluating TAA strategies, and explores techniques to manage and control this metric effectively while pursuing tactical investment opportunities.</p>
<section id="definition-and-importance-of-tracking-error" class="level3" data-number="9.4.1">
<h3 data-number="9.4.1" class="anchored" data-anchor-id="definition-and-importance-of-tracking-error"><span class="header-section-number">9.4.1</span> Definition and Importance of Tracking Error</h3>
<ul>
<li><strong>What is Tracking Error?:</strong>
<ul>
<li><strong>Definition:</strong> Tracking error represents the standard deviation of the difference between the returns of a portfolio and its benchmark. It quantifies the extent to which the portfolio’s performance deviates from the benchmark, reflecting the consistency of portfolio returns relative to a reference index.</li>
<li><strong>Significance in TAA:</strong> In the context of TAA, tracking error is essential for measuring the success and risk of deviation from a strategic asset allocation. It helps investors understand the impact of tactical moves on portfolio volatility and risk.</li>
</ul></li>
<li><strong>Balancing Alpha Generation and Benchmark Alignment:</strong>
<ul>
<li><strong>Alpha vs.&nbsp;Tracking Error:</strong> While TAA aims to generate alpha—excess returns over a benchmark—it also inherently increases tracking error due to deviations from the benchmark’s composition.</li>
<li><strong>Risk Considerations:</strong> High tracking error indicates a greater divergence from the benchmark, which can imply higher risk. Investors must balance the desire for higher returns through tactical moves against the risk of significant deviations, which might not always align with the investor’s risk tolerance or investment objectives.</li>
</ul></li>
</ul>
</section>
<section id="techniques-for-managing-and-controlling-tracking-error" class="level3" data-number="9.4.2">
<h3 data-number="9.4.2" class="anchored" data-anchor-id="techniques-for-managing-and-controlling-tracking-error"><span class="header-section-number">9.4.2</span> Techniques for Managing and Controlling Tracking Error</h3>
<ul>
<li><strong>Using Derivatives:</strong>
<ul>
<li><strong>Purpose and Implementation:</strong> Derivatives such as futures, options, and swaps can be used to adjust exposure to various market factors quickly and efficiently, helping to align portfolio returns with the benchmark when necessary.</li>
<li><strong>Risk Reduction:</strong> Appropriately used, derivatives can hedge against unwanted risks or enhance exposure to desired assets without substantial capital outlay, thus managing tracking error while pursuing tactical objectives.</li>
</ul></li>
<li><strong>Core-Satellite Portfolio Structure:</strong>
<ul>
<li><strong>Definition:</strong> The core-satellite approach involves maintaining a large ‘core’ portion of the portfolio closely aligned with the benchmark, complemented by smaller ‘satellite’ investments that diverge from the benchmark to seek higher returns.</li>
<li><strong>Benefits:</strong> This structure allows for controlled exploration of tactical opportunities in the satellite portions while keeping overall tracking error within acceptable limits due to the stability provided by the core.</li>
</ul></li>
<li><strong>Regular Portfolio Review and Rebalancing:</strong>
<ul>
<li><strong>Monitoring:</strong> Continuous monitoring of tracking error is crucial, especially as market conditions and portfolio positions change.</li>
<li><strong>Rebalancing Strategies:</strong> Implement systematic rebalancing to realign the portfolio with the benchmark or adjust the asset allocation to manage the level of tracking error, ensuring it remains within the predefined tolerance levels.</li>
</ul></li>
</ul>
</section>
<section id="conclusion-3" class="level3" data-number="9.4.3">
<h3 data-number="9.4.3" class="anchored" data-anchor-id="conclusion-3"><span class="header-section-number">9.4.3</span> Conclusion</h3>
<p>Tracking error is a vital metric for assessing the effectiveness and appropriateness of Tactical Asset Allocation strategies. By understanding and managing tracking error, investors can maintain a delicate balance between seeking to generate alpha and adhering closely enough to a benchmark to meet the overall investment objectives. Effective management of tracking error involves using sophisticated financial instruments like derivatives, employing a core-satellite portfolio structure, and conducting regular portfolio reviews. These strategies help investors achieve the desired outcomes from TAA while controlling the associated risks.</p>
<div class="callout callout-style-default callout-note callout-titled" title="CFA Curriculum Alignment">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>CFA Curriculum Alignment
</div>
</div>
<div class="callout-body-container callout-body">
<p>The CFA curriculum stresses the importance of measuring and managing risks, including the concept of tracking error. This measure is vital for understanding the volatility of returns relative to a benchmark, a key concern in tactical asset allocation. Candidates learn to calculate and interpret tracking error, enabling them to gauge the effectiveness of tactical decisions and their impact on the portfolio’s risk profile. The curriculum also discusses strategies for minimizing tracking error, such as through diversification and careful selection of the benchmark.</p>
</div>
</div>
</section>
</section>
<section id="costs-and-benefits-of-tactical-moves" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="costs-and-benefits-of-tactical-moves"><span class="header-section-number">9.5</span> Costs and Benefits of Tactical Moves</h2>
<p>Tactical Asset Allocation (TAA) can be a powerful strategy for enhancing portfolio returns and managing risk through deliberate short-term adjustments. However, implementing TAA comes with its own set of costs and risks that must be carefully weighed against the potential benefits. This subchapter will explore the various costs associated with TAA, discuss the risks of mis-timing, and evaluate how these factors balance with the potential for alpha generation.</p>
<section id="analyzing-the-costs-associated-with-taa" class="level3" data-number="9.5.1">
<h3 data-number="9.5.1" class="anchored" data-anchor-id="analyzing-the-costs-associated-with-taa"><span class="header-section-number">9.5.1</span> Analyzing the Costs Associated with TAA</h3>
<ul>
<li><strong>Transaction Costs:</strong>
<ul>
<li><strong>Brokerage Fees and Spreads:</strong> Every trade executed as part of a TAA strategy incurs brokerage fees or spreads, which can add up significantly, especially with frequent trading.</li>
<li><strong>Market Impact Costs:</strong> Large orders can move the market, potentially resulting in less favorable prices. This is particularly relevant in less liquid markets or with large position sizes.</li>
</ul></li>
<li><strong>Tax Considerations:</strong>
<ul>
<li><strong>Short-term Capital Gains:</strong> Frequent trading often leads to short-term capital gains, which are typically taxed at a higher rate than long-term gains. This can erode the net returns from tactical moves.</li>
<li><strong>Tax Efficiency:</strong> TAA strategies need to consider the tax implications of selling assets, as taxes can diminish the overall effectiveness of the strategy.</li>
</ul></li>
<li><strong>Risk of Mis-timing:</strong>
<ul>
<li><strong>Market Timing Challenges:</strong> Successfully timing the market is exceedingly difficult, even for professional investors. Mis-timed entries or exits can lead to losses or missed opportunities.</li>
<li><strong>Emotional Trading:</strong> The decision-making process in TAA can be influenced by emotional biases, especially in volatile markets. This can exacerbate the risk of mis-timing and lead to sub-optimal investment decisions.</li>
</ul></li>
</ul>
</section>
<section id="weighing-benefits-against-costs-and-risks" class="level3" data-number="9.5.2">
<h3 data-number="9.5.2" class="anchored" data-anchor-id="weighing-benefits-against-costs-and-risks"><span class="header-section-number">9.5.2</span> Weighing Benefits Against Costs and Risks</h3>
<ul>
<li><strong>Potential for Alpha Generation:</strong>
<ul>
<li><strong>Outperformance:</strong> TAA can generate alpha by capitalizing on short-term market inefficiencies and trends, potentially leading to returns that outpace the benchmark.</li>
<li><strong>Diversification and Risk Management:</strong> Properly executed, TAA can also help manage risk by adjusting the portfolio’s exposure to anticipated market downturns or volatile sectors.</li>
</ul></li>
<li><strong>Cost-Benefit Analysis:</strong>
<ul>
<li><strong>Quantitative Assessment:</strong> Evaluate the historical performance of TAA strategies to determine if the alpha generated has sufficiently compensated for the higher costs and risks.</li>
<li><strong>Qualitative Considerations:</strong> Consider the investor’s capacity to bear costs and willingness to accept the higher risks associated with frequent trading and potential mis-timing.</li>
</ul></li>
<li><strong>Strategic Alignment:</strong>
<ul>
<li><strong>Alignment with Investment Goals:</strong> Ensure that the TAA strategy aligns with the broader investment objectives and the investor’s risk tolerance. The benefits of potential alpha should justify the increased operational complexities and risks.</li>
</ul></li>
</ul>
</section>
<section id="conclusion-4" class="level3" data-number="9.5.3">
<h3 data-number="9.5.3" class="anchored" data-anchor-id="conclusion-4"><span class="header-section-number">9.5.3</span> Conclusion</h3>
<p>The decision to implement Tactical Asset Allocation should be based on a thorough analysis of both the direct and indirect costs involved, balanced against the potential benefits of alpha generation and enhanced risk management. Investors must also consider their own ability to effectively execute TAA strategies, including the capacity to make timely decisions and manage the associated risks. By carefully evaluating these factors, investors can determine whether TAA is a suitable strategy for their investment goals and risk profiles.</p>
</section>
</section>
<section id="sustainability-considerations-in-tactical-asset-allocation" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="sustainability-considerations-in-tactical-asset-allocation"><span class="header-section-number">9.6</span> Sustainability Considerations in Tactical Asset Allocation</h2>
<p>The integration of Environmental, Social, and Governance (ESG) factors into investment strategies is becoming increasingly important. In the realm of Tactical Asset Allocation (TAA), incorporating sustainability considerations can not only align investments with ethical standards but also enhance risk management and potentially uncover new opportunities for alpha. This subchapter explores how short-term sustainability trends and ESG factor shifts can be integrated into TAA decisions and evaluates the impact of sudden sustainability-related news on various asset classes and sectors.</p>
<section id="incorporating-short-term-sustainability-trends-and-esg-factor-shifts" class="level3" data-number="9.6.1">
<h3 data-number="9.6.1" class="anchored" data-anchor-id="incorporating-short-term-sustainability-trends-and-esg-factor-shifts"><span class="header-section-number">9.6.1</span> Incorporating Short-term Sustainability Trends and ESG Factor Shifts</h3>
<ul>
<li><strong>Monitoring ESG Trends:</strong>
<ul>
<li><strong>Data Sources:</strong> Utilize ESG rating agencies, sustainability indexes, and real-time ESG data platforms to monitor rapid shifts in ESG factors that might affect market dynamics.</li>
<li><strong>Tactical Adjustments:</strong> Adjust portfolio allocations to capitalize on positive ESG trends or mitigate risks associated with negative ESG developments. For example, increase exposure to renewable energy stocks in response to positive regulatory changes or advancements in technology.</li>
</ul></li>
<li><strong>ESG Integration in Tactical Decisions:</strong>
<ul>
<li><strong>Sector Analysis:</strong> Identify sectors that are likely to be impacted by ESG trends, such as energy, utilities, and manufacturing. For instance, sectors with high carbon footprints may be at risk from new environmental regulations, while sectors like clean technology may benefit.</li>
<li><strong>Security Selection:</strong> Choose companies within those sectors that demonstrate strong ESG practices or show rapid improvement in ESG metrics, as these companies may outperform their peers due to increasing investor interest and regulatory support.</li>
</ul></li>
</ul>
</section>
<section id="evaluating-the-impact-of-sudden-sustainability-related-news" class="level3" data-number="9.6.2">
<h3 data-number="9.6.2" class="anchored" data-anchor-id="evaluating-the-impact-of-sudden-sustainability-related-news"><span class="header-section-number">9.6.2</span> Evaluating the Impact of Sudden Sustainability-Related News</h3>
<ul>
<li><strong>Reactive Strategy:</strong>
<ul>
<li><strong>News Impact Analysis:</strong> Develop a strategy to quickly assess the potential impact of sudden sustainability-related news, such as environmental disasters, new sustainability legislation, or scandals involving poor corporate governance.</li>
<li><strong>Volatility and Opportunities:</strong> Understand that such news can cause significant volatility; however, it can also present opportunities for tactical gains by adjusting exposures before the market fully prices in the news.</li>
</ul></li>
<li><strong>Scenario Planning:</strong>
<ul>
<li><strong>Preparation:</strong> Prepare for various scenarios based on potential sustainability-related developments that could impact the markets. This preparation involves scenario analysis and stress testing to anticipate how different types of news could affect sectors or asset classes.</li>
<li><strong>Rapid Response:</strong> Set up a framework for rapid response to ensure that the portfolio can quickly adapt to new information, minimizing losses and maximizing potential gains from these situations.</li>
</ul></li>
</ul>
</section>
<section id="conclusion-5" class="level3" data-number="9.6.3">
<h3 data-number="9.6.3" class="anchored" data-anchor-id="conclusion-5"><span class="header-section-number">9.6.3</span> Conclusion</h3>
<p>Sustainability considerations are no longer just an ethical choice but a crucial component of tactical asset allocation that can drive performance and manage risks. By actively incorporating ESG trends and responding adeptly to sudden sustainability-related news, investors can enhance the responsiveness and resilience of their portfolios. This proactive approach not only contributes to sustainable development goals but also aligns with the growing investor demand for responsible investment practices, offering a competitive edge in today’s rapidly evolving market landscape.</p>
</section>
</section>
<section id="case-studies-in-tactical-asset-allocation" class="level2" data-number="9.7">
<h2 data-number="9.7" class="anchored" data-anchor-id="case-studies-in-tactical-asset-allocation"><span class="header-section-number">9.7</span> Case Studies in Tactical Asset Allocation</h2>
<section id="case-study-1-successful-taa-decision-during-the-covid-19-market-volatility" class="level3" data-number="9.7.1">
<h3 data-number="9.7.1" class="anchored" data-anchor-id="case-study-1-successful-taa-decision-during-the-covid-19-market-volatility"><span class="header-section-number">9.7.1</span> Case Study 1: Successful TAA Decision During the COVID-19 Market Volatility</h3>
<ul>
<li><strong>Background:</strong> In early 2020, the COVID-19 pandemic caused unprecedented market volatility. Equity markets plunged as lockdowns and economic uncertainty took hold globally. Investors faced significant challenges in navigating this turbulence.</li>
<li><strong>Tactical Decision:</strong> A portfolio manager decided to tactically allocate assets by significantly increasing the portfolio’s exposure to healthcare and technology sectors, anticipating that these sectors would outperform during the pandemic. The decision was based on the increasing demand for healthcare services and pharmaceuticals, along with the surge in remote working boosting technology sector performance.</li>
<li><strong>Implementation:</strong>
<ol type="1">
<li>The manager increased holdings in selected biotechnology companies involved in vaccine research and major technology firms that provided remote work solutions.</li>
<li>Utilized ETFs to quickly adjust sector exposure, maintaining flexibility to revert to the original asset allocation once market conditions stabilized.</li>
</ol></li>
<li><strong>Outcome:</strong>
<ol type="1">
<li>The healthcare and technology sectors significantly outperformed the broader market in 2020.</li>
<li>The portfolio realized substantial gains from these sectors, which offset declines in other areas like travel and traditional retail, resulting in overall outperformance against the benchmark.</li>
</ol></li>
<li><strong>Lessons Learned:</strong>
<ol type="1">
<li>Proactive sector rotation based on evolving economic conditions can protect and grow portfolio value even during market downturns.</li>
<li>The importance of maintaining flexibility in tactical asset allocation strategies to quickly capitalize on emerging opportunities.</li>
</ol></li>
</ul>
</section>
<section id="case-study-2-unsuccessful-taa-decision-during-the-2008-financial-crisis" class="level3" data-number="9.7.2">
<h3 data-number="9.7.2" class="anchored" data-anchor-id="case-study-2-unsuccessful-taa-decision-during-the-2008-financial-crisis"><span class="header-section-number">9.7.2</span> Case Study 2: Unsuccessful TAA Decision During the 2008 Financial Crisis</h3>
<ul>
<li><strong>Background:</strong> The 2008 financial crisis was triggered by the collapse of the housing bubble in the United States, leading to widespread repercussions in global financial markets.</li>
<li><strong>Tactical Decision:</strong> In mid-2008, a portfolio manager anticipated a quick recovery of the financial sector and increased exposure to major banks and insurance companies, expecting that these institutions would rebound as markets stabilized.</li>
<li><strong>Implementation:</strong>
<ol type="1">
<li>The manager reallocated funds from defensive sectors like consumer staples and utilities to financial stocks, using derivatives to enhance exposure.</li>
<li>Failed to set adequate stop-loss orders, expecting that government interventions would shore up the markets.</li>
</ol></li>
<li><strong>Outcome:</strong>
<ol type="1">
<li>The financial sector experienced further declines as the crisis deepened, exacerbated by the Lehman Brothers bankruptcy.</li>
<li>The lack of stop-loss measures and overconcentration in a single struggling sector led to significant losses, underperforming the market and the strategic benchmark significantly.</li>
</ol></li>
<li><strong>Lessons Learned:</strong>
<ol type="1">
<li>Overconfidence in market recovery and underestimation of systemic risks can lead to poor tactical decisions.</li>
<li>The critical importance of risk management measures, such as diversification and stop-loss orders, in protecting the portfolio against unexpected market downturns.</li>
</ol></li>
</ul>
</section>
</section>
<section id="conclusion-the-strategic-importance-of-tactical-asset-allocation" class="level2" data-number="9.8">
<h2 data-number="9.8" class="anchored" data-anchor-id="conclusion-the-strategic-importance-of-tactical-asset-allocation"><span class="header-section-number">9.8</span> Conclusion: The Strategic Importance of Tactical Asset Allocation</h2>
<p>Tactical Asset Allocation (TAA) plays a critical role within the broader asset allocation framework, serving as a dynamic complement to strategic asset allocation. By enabling investors to make short to medium-term adjustments based on current market conditions and forecasts, TAA provides a powerful tool for enhancing portfolio returns and managing risks effectively.</p>
<section id="key-aspects-of-taa" class="level3" data-number="9.8.1">
<h3 data-number="9.8.1" class="anchored" data-anchor-id="key-aspects-of-taa"><span class="header-section-number">9.8.1</span> Key Aspects of TAA:</h3>
<ul>
<li><strong>Flexibility:</strong> TAA offers the flexibility to adjust asset exposures in response to anticipated market movements or macroeconomic changes, which can help safeguard assets during downturns and capitalize on growth opportunities.</li>
<li><strong>Performance Enhancement:</strong> Through timely and strategic deviations from the strategic asset allocation, TAA aims to generate alpha—additional returns over the benchmark. This approach can significantly contribute to overall portfolio performance.</li>
<li><strong>Risk Management:</strong> TAA allows investors to respond to short-term risks that may not be fully addressed by a long-term strategic framework. It facilitates adjustments in asset allocation to mitigate potential losses due to market volatility or geopolitical events.</li>
</ul>
</section>
<section id="encouraging-disciplined-decision-making" class="level3" data-number="9.8.2">
<h3 data-number="9.8.2" class="anchored" data-anchor-id="encouraging-disciplined-decision-making"><span class="header-section-number">9.8.2</span> Encouraging Disciplined Decision-Making</h3>
<ul>
<li><strong>Thorough Market Analysis:</strong>
<ul>
<li><strong>Foundation of Successful TAA:</strong> Effective tactical decisions are underpinned by robust and comprehensive market analysis. This includes analyzing economic data, understanding geopolitical impacts, and staying updated on market trends.</li>
<li><strong>Continuous Learning:</strong> Markets are dynamic and complex. Continual education and adaptation to new analytical techniques and economic theories can enhance decision-making and investment outcomes.</li>
</ul></li>
<li><strong>Clear Understanding of the Investment Environment:</strong>
<ul>
<li><strong>Contextual Awareness:</strong> A deep understanding of the broader economic and investment environment is crucial. This includes knowledge of the cyclical nature of markets, regulatory changes, and evolving financial instruments.</li>
<li><strong>Investment Policy Alignment:</strong> Tactical moves should align with the overall investment policy and objectives. This ensures that even short-term adjustments contribute positively towards achieving long-term financial goals.</li>
</ul></li>
<li><strong>Risk Consideration:</strong>
<ul>
<li><strong>Balanced Risk-Taking:</strong> While seeking to maximize returns, it is essential to balance the potential risks. This involves understanding the trade-offs between risk and return, particularly how tactical moves might affect the portfolio’s risk profile.</li>
<li><strong>Preparedness and Contingency Planning:</strong> Effective risk management in TAA also involves being prepared for adverse outcomes through risk assessment tools, scenario planning, and having clear exit strategies.</li>
</ul></li>
</ul>
</section>
</section>
<section id="conclusion-6" class="level2" data-number="9.9">
<h2 data-number="9.9" class="anchored" data-anchor-id="conclusion-6"><span class="header-section-number">9.9</span> Conclusion</h2>
<p>Tactical Asset Allocation is an indispensable strategy within the investment management spectrum, blending the art of market timing with the science of portfolio management. By encouraging disciplined decision-making based on meticulous market analysis and a nuanced understanding of the investment climate, TAA empowers investors to navigate market complexities with agility and precision. Ultimately, TAA is not just about responding to the market environment—it’s about anticipating and shaping portfolio strategies to optimize performance and manage risks in an ever-changing world.</p>
</section>
<section id="black-litterman-model-and-active-portfolio-management" class="level2" data-number="9.10">
<h2 data-number="9.10" class="anchored" data-anchor-id="black-litterman-model-and-active-portfolio-management"><span class="header-section-number">9.10</span> Black-Litterman model and Active Portfolio Management</h2>
<p>One of the ways to incorporate the views into the investment process is to follow a Black-Litterman approach. In Cesim Invest the views are available in two formats under Decisions/Economic outlook: text and expected return ranges, as shown below.</p>
<div id="fig-elementwise" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-elementwise-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="graphics/Tactical_Asset_Allocation/Capture.JPG" id="fig-elementwise" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-elementwise-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.1
</figcaption>
</figure>
</div>
<p>Below we provide an overview of the Black-Litterman procedure and it’s adaptation for a case of active portfolio managament.</p>
<section id="assumptions-and-inputs" class="level3" data-number="9.10.1">
<h3 data-number="9.10.1" class="anchored" data-anchor-id="assumptions-and-inputs"><span class="header-section-number">9.10.1</span> Assumptions and Inputs</h3>
<p>There are two sources of information: public <span class="math inline">\(I\)</span> and private <span class="math inline">\(G\)</span></p>
<ul>
<li><span class="math inline">\(w_m\)</span>: vector of market capitalization weights</li>
<li><span class="math inline">\(\Sigma\)</span>: covariance matrix of the assets</li>
<li><span class="math inline">\(r\)</span>: vector of excess returns:
<ul>
<li><span class="math inline">\(r \sim N(\mu, \Sigma)\)</span></li>
<li><span class="math inline">\(\mu \sim N(E[\mu], \Sigma_{\mu})\)</span></li>
</ul></li>
</ul>
<p><strong>Knowledge on the distribution of <span class="math inline">\(\mu\)</span>:</strong> * Public: <span class="math inline">\(I \to E[\mu|I] \sim N(\pi, \tau\Sigma)\)</span> * Private: <span class="math inline">\(G \to P[\mu|G] \sim N(q, \Omega)\)</span></p>
</section>
<section id="procedure" class="level3" data-number="9.10.2">
<h3 data-number="9.10.2" class="anchored" data-anchor-id="procedure"><span class="header-section-number">9.10.2</span> Procedure</h3>
<ol type="1">
<li><p><strong>Equilibrium Returns:</strong> Compute the vector of equilibrium returns <span class="math inline">\(\pi\)</span>: <span class="math display">\[\pi = \delta \Sigma w_m\]</span></p></li>
<li><p><strong>Express Views:</strong> <span class="math inline">\(P[\mu|G] = q + \epsilon\)</span>, where <span class="math inline">\(\epsilon \sim N(0, \Omega)\)</span> <span class="math inline">\(P[\mu|G] \sim N(q, \Omega)\)</span></p></li>
<li><p><strong>Optimized Expected Returns:</strong> Compute the optimized expected returns and its variance using the BL formulae: <span class="math display">\[\mu_{BL} = \pi + \Sigma P^T(P \Sigma P^T + \Omega / \tau)^{-1}(q - P \pi)\]</span> <span class="math display">\[\Sigma_{BL} = (1 + \tau) \Sigma - \tau^2 \Sigma P^T(\tau P \Sigma P^T + \Omega)^{-1} P \Sigma\]</span></p></li>
<li><p><strong>Solve Problem:</strong> Solve the optimization problem using the optimized expected returns: <span class="math display">\[\text{argmax}_w w^T \mu_{BL} - (\delta / 2) w^T \Sigma_{BL} w\]</span> subject to: <span class="math inline">\(w^T \mathbf{1} = 1\)</span> and other constraints</p></li>
</ol>
</section>
<section id="example" class="level3" data-number="9.10.3">
<h3 data-number="9.10.3" class="anchored" data-anchor-id="example"><span class="header-section-number">9.10.3</span> Example:</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Asset</th>
<th style="text-align: left;">Market-Cap Weight</th>
<th style="text-align: left;">Volatility</th>
<th style="text-align: left;">Correlation</th>
<th style="text-align: left;">Equilibrium Excess Return</th>
<th style="text-align: left;">Black–Litterman Excess Return</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Stocks</strong></td>
<td style="text-align: left;">75%</td>
<td style="text-align: left;">13%</td>
<td style="text-align: left;">0.3</td>
<td style="text-align: left;">6.46%</td>
<td style="text-align: left;">2.39%</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Bonds</strong></td>
<td style="text-align: left;">25%</td>
<td style="text-align: left;">5%</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">1.02%</td>
<td style="text-align: left;">1.17%</td>
</tr>
</tbody>
</table>
<p>Suppose there are only two asset classes in the benchmark portfolio—stocks and bonds—with benchmark weights, volatilities, and correlation as reported in Table above. To derive the equilibrium views assume that the benchmark portfolio is a mean-variance efficient portfolio. As a result, implied equilibrium excess returns can be derived by a reverse optimization from the benchmark weights. We set the value of <span class="math inline">\(\delta\)</span> such that the resulting equilibrium excess returns will provide an expected Sharpe ratio of 0.5 for the portfolio. Given these parameters, the equilibrium excess returns for stocks and bonds are found to be 6.46% and 1.02%, respectively. Next, we assume that there is only one active investment view—stocks are expected to underperform bonds by 3%. We then derive the Black–Litterman expected excess returns of stocks and bonds at 2.39% and 1.17%, respectively. All results are summarized in Table below. Lastly, for the sake of illustration, setting the resulting active portfolio to give a tracking error of 2%, the optimal active weights are determined to be +16% stocks and −16% bonds, respectively.</p>
</section>
<section id="active-management" class="level3" data-number="9.10.4">
<h3 data-number="9.10.4" class="anchored" data-anchor-id="active-management"><span class="header-section-number">9.10.4</span> Active management</h3>
<p>In the original Black-Litterman framework one looks at expected excess returns over the risk-free rate, whereas active managers are interested in the expected excess returns over the benchmark. The consequence of this is that when applying BL, we must set <span class="math inline">\(\pi = 0\)</span> in the Black–Litterman formula: <span class="math display">\[\mu^*_{BL} = ((\tau \Sigma)^{-1} + P^T \Omega^{-1} P)^{-1}(P^T \Omega^{-1} q)\]</span> We may directly consider the alphas instead of the excess returns over the benchmark: <span class="math display">\[\alpha_{BL} = ((\tau \Sigma)^{-1} + P^T \Omega^{-1} P)^{-1}(P^T \Omega^{-1} q)\]</span> <span class="math display">\[\alpha_{BL} = \Sigma P^T(P \Sigma P^T + \Omega / \tau)^{-1} q\]</span> Once predictions have been made and we have a new vector of expected alphas, we consider the corresponding active management problem: <span class="math display">\[\text{argmax}_{w_a} w_a^T \alpha_{BL} - (\lambda / 2) w_a^T \Sigma w_a\]</span> s.t. constraints.</p>
</section>
<section id="example-1" class="level3" data-number="9.10.5">
<h3 data-number="9.10.5" class="anchored" data-anchor-id="example-1"><span class="header-section-number">9.10.5</span> Example:</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Asset</th>
<th style="text-align: left;">Market-Cap Weight (Benchmark)</th>
<th style="text-align: left;">Volatility</th>
<th style="text-align: left;">Correlation</th>
<th style="text-align: left;">Equilibrium Excess Return</th>
<th style="text-align: left;">Black–Litterman Active Excess Return</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Stocks</strong></td>
<td style="text-align: left;">75%</td>
<td style="text-align: left;">13%</td>
<td style="text-align: left;">0.3</td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">−1.45%</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Bonds</strong></td>
<td style="text-align: left;">25%</td>
<td style="text-align: left;">5%</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">0.0%</td>
<td style="text-align: left;">+0.05%</td>
</tr>
</tbody>
</table>
<p>Going back to our original example and set <span class="math inline">\(\pi = 0\)</span>, keeping all other estimates the same, and derive the expected active returns resulting from our bearish investment view on stocks versus bonds. We can now calculate the reverse-optimized active portfolio associated with the newly calculated active excess returns and scale it so that the final portfolio meets the defined target tracking error. It is easy to verify that the final active portfolio will be composed of a short position in stocks (−16.1%) and a long position in bonds (+16.1%) for a total tracking error of 2%. Consequently, the final total portfolio weights are +58.9% (75% − 16.1%) and +41.1% (25% + 16.1%) on stocks and bonds, respectively. The optimisation can be perfomed using Matlab’s Financial Toolbox or Python’s PyPortfolioOpt.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation column-body">
  <div class="nav-page nav-page-previous">
      <a href="./08_Tactical_Financial_Analysis.html" class="pagination-link" aria-label="Tactical Financial Analysis">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Tactical Financial Analysis</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./10_Security_Analysis.html" class="pagination-link" aria-label="Security Analysis">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Security Analysis</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 © 2025 Investment Management Game (IMAG). All rights reserved.
  </li>  
    <li class="nav-item">
 Supported by <a href="https://erasmus-plus.ec.europa.eu/projects/search/details/2022-1-LI01-KA220-HED-000085536" target="_blank">Erasmus+</a> and partner institutions. Logos and trademarks are property of their respective owners.
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>